### ISSUE TITLE
Groundskeeping Android Master Issue: April 22 - 26

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1008]
## Description
Umbrella issue for tasks that I take on during my Groundskeeping rotation.

### PR to be submitted:
- [ ] #917  - Crash fix - `JetpackTunnelResponse.getData()` on a null object reference

### On Hold:
( (Mystery issues that could not be solved - have occurred for 1 user in a relatively long period of time))
- [ ] #948 - Crash fix - `Exception: Results have been set` (PR: #1021) - See comments [here](https://github.com/woocommerce/woocommerce-android/pull/1021#issuecomment-487016761)
- [ ] #919 - Crash fix - TextView.onProvideAutoStructureForAssistOrAutofill: see comments [here](https://github.com/woocommerce/woocommerce-android/issues/919#issuecomment-486538633)
- [ ] #1005 - Crash fix - Fragment already added: NotifsListFragment

### Completed:
- [x] #871  - Crash fix - update zendesk version to 2.3.1 (PR #1015)
- [x] #908 - Notifications: Layout issues with review notification detail (PR: #1016)
- [x] #933  - Crash Fix - No Activity found to handle null (PR #1018)
- [x] #392  - Crash fix: Fatal Exception: DateUtils - Closed: see comments [here](https://github.com/woocommerce/woocommerce-android/issues/392#issuecomment-485674173) 
- [x] #981  - Crash fix - intent parameter is null in `NotificationsProcessingService` (PR #1022)
- [x] #916 - Crash Fix - `Can not perform this action after onSaveInstanceState` - Closed - see comments [here](https://github.com/woocommerce/woocommerce-android/issues/916#issuecomment-486574907)
- [x] #980  - Crash Fix -` widget.AppCompatBackgroundHelper.onSetBackgroundDrawable` - Closed - see comments [here](https://github.com/woocommerce/woocommerce-android/issues/980#issuecomment-486632619)
- [x] #812 - Retain the state of the "My Store" tab when the activity is destroyed (PR: #1023)
- [x] #1017 - Review detail: purple stars on Lollipop (PR: #1024)

**Comment by anitaa1990** [comment]
Closing this since my groundskeeping rotation is complete.
