### ISSUE TITLE
Custom Amounts M4

### ISSUE THREAD

**Issue by AnirudhBhat** [woocommerce/woocommerce-android#10213]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10214
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10246
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10280
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10227
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10228
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10301
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10230
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10238
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10323
```

**Comment by AnirudhBhat** [comment]
All tasks are completed
