### ISSUE TITLE
[Hack Week] Offer a way to fix Cha-ching notification sound issue from the app

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#10327]
Some Android OEMs (and also the case for AOSP Android) make it very easy to change a notification channel to being silent, which could happen accidentally by the users, and could be the reason behind the reports we get about the missing cha-ching sound (#1076).

This task's goal is to offer a way for the users to fix the issue from the app if the change was done accidentally:

```[tasklist]
### Tasks
- [x] Refactor notifications to allow deleting and re-creating notification channels. #10322
- [x] Show an alert in the order list screen when we detect that the sound has been disabled. #10336
- [x] Add an entry to the app settings that allow fixing the sound #10341
- [x] Track the order notifications sound to identify how many users are facing the issues https://github.com/woocommerce/woocommerce-android/pull/11080
- [x] Allow fixing sound when the order notification sound is different from the default one https://github.com/woocommerce/woocommerce-android/pull/11080
```

**Comment by hichamboushaba** [comment]
Reopening to add some improvements
