### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#105]
List is incomplete - we need to still break down the Top Performers section, and should be synchronized with the iOS counterpart: https://github.com/woocommerce/woocommerce-ios/issues/14.

### TODO
* [x] Set up overall layout with empty card(s)
* [x] Store stats --> #65 (Store stats sub-epic)
* [x] Orders to fulfill (https://github.com/woocommerce/woocommerce-android/issues/283)
* [x] Top performers (https://github.com/woocommerce/woocommerce-android/issues/284)

![dashboard-i4](https://user-images.githubusercontent.com/9613966/39319806-36f938aa-4950-11e8-9950-c011350cccbb.png)
