### ISSUE TITLE
Add endpoints to retrieve targeting options

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#10502]
```[tasklist]
### Tasks
- [x] Mock endpoints for the first part of the project. https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2933
- [x] Add logic to cache entities. https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2933
- [ ] https://github.com/woocommerce/woocommerce-android/issues/10689
```
