### ISSUE TITLE
Implement Passkey fetching through the Credential Manager API

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#10557]
# Summary
We discovered that a new version 1.2.0 of the Credential Manager was released after the Passkey project development, containing lots of async functions counterparts within the API with it. E.g.:

> The [getCredential](https://href.li/?https://developer.android.com/reference/androidx/credentials/CredentialManager#getCredential(android.content.Context,androidx.credentials.PrepareGetCredentialResponse.PendingGetCredentialHandle)) function, which is a suspend function used to retrieve a Passkey data from a Challenge, is now followed by a [getCredentialAsync](https://href.li/?https://developer.android.com/reference/androidx/credentials/CredentialManager#getCredentialAsync(android.content.Context,androidx.credentials.PrepareGetCredentialResponse.PendingGetCredentialHandle,android.os.CancellationSignal,java.util.concurrent.Executor,androidx.credentials.CredentialManagerCallback)) function, which is not suspend and relies on a callback instead.

This seems to be a very intentional move from Google to support Java usage with the Credential Manager, and it might be a very good alternative to avoid a drastic change inside the WordPress Login library. We can verify in the docs statements like This API uses callbacks instead of Kotlin coroutines.

Our goal here is to ensure we're adopting the Credential Manager through this callback structure since the WordPress Login library still doesn't have proper support for the Kotlin Coroutines usage.

```[tasklist]
### Tasks
- [x] Introduce basic Credential Manager operation with callback structure
- [x] Connect Credential Manager handler usage with Passkey auth flow
- [ ] Ensure the Credential Manager is only called when API 34 or higher is available
```
