### ISSUE TITLE
Add Credential Manager library and related dependencies

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#10556]
# Summary
Before starting adding actual code around the Credential Manager API, we need to establish inside the WordPress Login library a way to import the Credential Manager without causing build errors. As the WordPress Login library contains lots of outdated dependencies, this issue should approach the solution by adding the Credential Manager dependency and fix all build errors caused by it.

```[tasklist]
### Tasks
- [ ] Upgrade Kotlin version
- [ ] Add Credential Manager dependency
- [ ] Upgrade crashing dependencies
- [ ] Migrate code with compilation errors after dependencies upgrade
```
