### ISSUE TITLE
Add endpoint to fetch payment methods

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#10722]
```[tasklist]
### Tasks
- [x] Stubbed implementation https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2953
- [ ] Replace mocked requests with real ones
- [ ] Support for adding new payment method
```
