### ISSUE TITLE
Blaze Analytics

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#10784]
Add al Blaze related new events following the tracking plan: pe5sF9-2mb-p2

```[tasklist]
### Tasks
- [x] Add existing events from Blaze i2 to the new native screens: https://github.com/woocommerce/woocommerce-android/pull/10821
- [x] Add new events for the native flow: https://github.com/woocommerce/woocommerce-android/pull/10820
- [x] Add campaign creation success/failure tracking: #10926
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
