### ISSUE TITLE
[Better Errors] App Passwords Explanation logic

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#10802]
## Tasks

- [ ] Wire the continue button to the app password login web page
- [ ] Wire contact support button
- [ ] Properly display why we couldn't login into the site. **see details**

#### Login 

If the response status code is:

-  `200` and we **can** extract the error message
    - return message

- `4xx` or `200`(could **not** extract an error message)
     - return "This is likely because your store has some extra security steps in place"

- Any other error (Like invalid html)
     - return "This is because we got an unexpected response from your site"

#### Check Adming Page Access

- `404` or any other http error code
     - return "This is likely because your store has some extra security steps in place"

- Any other error (Like invalid html)
     - return "This is because we got an unexpected response from your site"

**iOS Implementation**
- [Login Errors](https://github.com/woocommerce/woocommerce-ios/blob/e8cdfb2cd3d655855224dfa306481cca8b772506/WooCommerce/Classes/Authentication/SiteCredentialLoginUseCase.swift#L164-L179)
- [Admin Page Errors](https://github.com/woocommerce/woocommerce-ios/blob/e8cdfb2cd3d655855224dfa306481cca8b772506/WooCommerce/Classes/Authentication/SiteCredentialLoginUseCase.swift#L207-L213)
- [Error Messages based on errors](https://github.com/woocommerce/woocommerce-ios/blob/trunk/WooCommerce/Classes/Authentication/Application%20Password/ApplicationPasswordTutorialViewModel.swift#L7-L27)

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
