### ISSUE TITLE
[Analytics Hub] Milestone 1 design feedback

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#10840]
Changes based on design feedback from milestone 1:

- [x] “See report” should be in sentence case.
- [x] The text size of “See report” should be one step smaller (I think it’s “Caption”?). This matches the text size on [similar buttons elsewhere](https://href.li/share.cleanshot.com/fCkT046l).
- [x] The chevron icon should be smaller. Again, to match [similar icons elsewhere](https://href.li/share.cleanshot.com/bPJXm0t5).
- [x] This isn’t part of this project, but the date ranges at the top of the screen should use en-dashes (not hyphens).

![Image](https://github.com/woocommerce/woocommerce-android/assets/8658164/c1debffd-c6b2-4acf-b89d-a5ed51506497)

Discussion: pe5pgL-4wy-p2#comment-3730

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
