### ISSUE TITLE
Add instrumentation tests for shipment tracking plugin

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1086]
Write UI tests for #1035 , #1036 , #1037 , #1058 

### Order Detail Page
- [x] If shipment tracking plugin is available, the shipment tracking card is displayed
- [x] If shipment tracking plugin is not available, the shipment tracking card is not visible.
- [x] Verify that add tracking button is not visible in this page.

### Shipment Tracking Item Card:
- [x] The provider name, tracking number and date shipped are displayed correctly
- [x] The popup menu for each item is opened correctly. 
- [x] The `Track Shipment` menu item should only be displayed if the tracking link is available
- [x] Clicking on `Track Shipment` menu item redirects to a webview
- [x] Clicking on `Delete Shipment` menu item:
    - [x] If no network is available, offline error message should be displayed
    - [x] If undo is selected, the deleted item should be added back to the tracking list.
    - [x] If undo not selected, and if network available, the item should be removed from the list. 
        - [x] If request successful, success snackbar should be displayed
        - [x] If request failed, error snackbar should be displayed and the deleted item should be added back to the tracking list.
- [x] Clicking on a tracking item copies the tracking number to clipboard.

### Order Fulfilment Page
- [x] Clicking on `Order Fulfilment` button redirects to Fulfil Order screen
- [x] If shipment plugin is available, the optional tracking information should be displayed correctly.
- [x] If no shipment trackings are available, but plugin is available, then the empty card should be displayed.
- [x] The provider name, tracking number and date shipped are displayed correctly
- [x] Clicking on `Delete Shipment` menu item:
    - [x] If no network is available, offline error message should be displayed
    - [x] If undo is selected, the deleted item should be added back to the tracking list.
    - [x] If undo not selected, and if network available, the item should be removed from the list.
        - [x] If request successful, success snackbar should be displayed
        - [x] If request failed, error snackbar should be displayed and the deleted item should be added back to the tracking list.

### Add Shipment Tracking Page:
- [x] Clicking on `Add Tracking` button should open the `Add Shipment tracking` activity.
- [x] Toolbar title, cross and `Add` button is displayed correctly
- [x] Clicking back button or cross button displays confirmation dialog. 
   - [x] Clicking on `Discard` redirects to previous screen.
   - [x] Clicking on `Don't discard` dismisses dialog
- [ ] Clicking on `Add` button without entering any details displays error
- [ ] Clicking on `Select Provider` redirects to `Select Provider` dialog.
- [ ] Clicking on `Select date` opens dialog and selecting a date displays the date correctly

### Select Provider Dialog:
- [ ] Toolbar title is displayed correctly
- [ ] Ensure that the provider list is displayed in alphabetical order. 
    - [ ] If the store country matches the country in the providers list, then that section  should be displayed first.
    - [ ] The first section in the list should be `Custom Provider`
 - [ ] Selecting a provider should redirect to the previous screen and the provider name selected should be displayed correctly.
