### ISSUE TITLE
[Payment Method Improvements] Cash Payment Improvements

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#10941]
Related to this iOS [PR](https://github.com/woocommerce/woocommerce-ios/pull/11365)

We want to calculate the change due for a merchant when capturing a payment via cash.

Kind of a copy of [this](https://github.com/woocommerce/woomobile-private/issues/333) issue but just focusing on change due to customer.

This is now paused: [Needs to **incorporate** [these design changes](https://github.com/woocommerce/woocommerce-android/issues/11253) (which are also being implemented on iOS), not just copy existing iOS functionality. ]

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11413
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11525
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11542
- [x] default Cash Recieved field to show the total due (can be edited later using the num pad)
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11584
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11585
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11583
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
