### ISSUE TITLE
[Payment Method Improvements] Add support for other payment methods

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#10940]
See related iOS [PR](https://github.com/woocommerce/woocommerce-ios/pull/11366)

and[ this one](https://github.com/woocommerce/woocommerce-ios/pull/11365). 

**Issue Summary:**

Allow the user to add a note to the order with the paid amount and the change due, for their records. We should include this information in the receipt.

**Issue Description:**

This issue is to add support for other payment methods to the Android application, similar to the functionality recently implemented in iOS ([#11366](https://github.com/woocommerce/woocommerce-ios/pull/11366)). This allows merchants to specify their payment methods via a note attached to the order. This functionality is particularly useful when the merchant receives payment via an alternative method, such as checks, gift cards, or house accounts, and wishes to record this.

**Testing Instructions (based on iOS [PR](https://github.com/woocommerce/woocommerce-ios/pull/11365)):**

1. Open the application and navigate to orders.
2. Tap on '+' to create a new order.
3. Add the required products to the order and then tap on 'Create'.
4. Following this, tap on 'Collect Payment'.
5. Select 'Other Payment Methods' from the available options.
6. Add a note about the payment method used and mark the order as complete.
7. Verify that the order is set as complete and that the order details are duly shown.
8. Refresh the order and ensure that a note has been added with the payment method details you entered.
9. Repeat the previous steps without adding a note and ensure no note is added to the order.

Please also validate that the appropriate events are being tracked: when tapping on 'Other Payment Methods' option and when adding a note.

When tapping on the 'Other Payment Methods' row, this event should be tracked:

`🔵 Tracked payments_flow_collect, properties: [AnyHashable("is_wpcom_store"): true, AnyHashable("site_url"): "{site_url}", AnyHashable("order_id"): order_id, AnyHashable("payment_method"): "other_payment_methods", AnyHashable("was_ecommerce_trial"): false, AnyHashable("plan"): "business-bundle", AnyHashable("blog_id"): blog_id, AnyHashable("flow"): "order_payment"]`

And when adding a note, this event should be tracked:

`🔵 Tracked other_payment_methods_note_added, properties: [AnyHashable("site_url"): "{site_url}", AnyHashable("was_ecommerce_trial"): false, AnyHashable("is_wpcom_store"): true, AnyHashable("blog_id"): blog_id, AnyHashable("plan"): "business-bundle"]`

Lastly, ensure that the event `payments_flow_completed` is being tracked with the correct payment method details.
```[tasklist]
### Tasks
- [ ] Add 'Other Payment Methods' to the available options.
- [ ] Allow user to add a note about the payment method used and mark the order as complete.
- [ ] Confirm above testing steps.
- [ ] Confirm event tracking for Android based on iOS steps above.
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by backwardstruck** [comment]
Confirming details on[ iOS changes](https://github.com/woocommerce/woocommerce-ios/pull/11366) as those have not yet been merged.

**Comment by kidinov** [comment]
@malinajirka 👋

That's marked as high now, but the linked iOS PR is closed, and from what I see, the iOS app doesn't have an adding feature, too. There is "add customer note" in the order details, though, so I am wondering how important this is. Wdyt?

![Image](https://github.com/user-attachments/assets/f9ca96ed-bba6-466d-9756-ab6aa61fed96)

**Comment by malinajirka** [comment]
Good question Andrei! 

@toupper Do you remember why this feature never got merged on iOS even though it was implemented?

**Comment by toupper** [comment]
@malinajirka Before merging it I wanted to apply the design feedback, which we got here here pdfdoF-4kI-p2. I wanted to implement these in the next HACK week but with my team switch, I never had the opportunity. Let me know if you have further questions.

**Comment by malinajirka** [comment]
Thanks for the context!

I agree Andrei, this doesn't feel like a priority right now. Considering, users have a workaround (adding a note manually) and considering our focus on the POS, I believe we can close this issue for now.
