### ISSUE TITLE
Add option to edit and delete product categories

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11061]
Add support to `edit` or `delete` existing product categories from the app. 

```[tasklist]
### Tasks
- [x] FluxC support to delete and edit product categories: https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2974
- [x] Support for deleting categories: https://github.com/woocommerce/woocommerce-android/pull/11085
- [x] Support for editing categories: https://github.com/woocommerce/woocommerce-android/pull/11077
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by pmusolino** [comment]
This should have been already added on iOS, so please take a look at the same functionalities on the opposite platform 👍

**Comment by JorgeMucientes** [comment]
Thanks for the heads up @pmusolino. I'm aware of it :) I decided to work on this project after seeing this issue https://github.com/woocommerce/woomobile-private/issues/306
