### ISSUE TITLE
Remove WooExpress sign-up

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11115]
pfwcF5-by-p2

```[tasklist]
### Login Changes
- [x] Update the “Log in” button in the prologue to be the primary CTA. #11125
- [x] Re-word the “Get Started” button to "Starting a new store?" #11125
- [x] Update the logic of the "Starting a new store?" button to open https://woo.com/hosting-solutions/ #11125
- [x] Remove the “Create Account” [fallback](https://github.com/woocommerce/woocommerce-android/assets/1657201/965fbfaa-c789-45a5-8415-d6685c3f92a1) option from the WordPress.com login flow. #11125
- [x] Remove the “Create a new store” option from the site picker. #11125
- [x] Code Cleanup. https://github.com/woocommerce/woocommerce-android/pull/11145
```

```[tasklist]
### Tasks
- [x] Remove the upgrade button from the free trial sites banner. #11126
- [x] Hide the "Subscriptions" screen for free trial sites. #11126
- [x] Rename the “Upgrades” menu in Android to “Subscriptions”. #11126
- [x] Remove the logic of adding the “launch your store” task for free trial sites, and remove the logic of upgrading from its screen. #11126
- [x] Remove the onboarding task “Name your store”. #11126
- [ ] Code Cleanup https://github.com/woocommerce/woocommerce-android/pull/11150
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
