### ISSUE TITLE
[Analytics Hub] Milestone 2 design feedback

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#11151]
Changes based on design feedback from milestone 2:

- [x] Occasionally after rearranging the cards, the shadow on the last card doesn’t load.
- [x] Make sure that tapping on the checkbox highlights the entire row background. (Tapping on the row checks and unchecks the checkbox, and highlights the row background on tap. Tapping on the checkbox, though, works just fine, but only highlights the checkbox background.)
- [x] Update the pencil icon to a Google Material icon instead of gridicon.

Discussion: pe5pgL-4wy-p2#comment-3856

![image](https://github.com/woocommerce/woocommerce-android/assets/8658164/da53a414-2538-4796-b1a3-c95852c79b82)

![image](https://github.com/woocommerce/woocommerce-android/assets/8658164/70c96875-1adc-4e4b-b0cd-977c5a4051cb)

![image](https://github.com/woocommerce/woocommerce-android/assets/8658164/60f39262-80b7-45f9-b7dc-7144a88fb97e)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
