### ISSUE TITLE
[Dynamic Dashboard] Stats card

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11219]
```[tasklist]
### Tasks
- [x] Extract logic to a new ViewModel and Composable function https://github.com/woocommerce/woocommerce-android/pull/11231
- [x] Support pull-to-refresh https://github.com/woocommerce/woocommerce-android/pull/11245
- [x] Move Jetpack benefits logic to the parent ViewModel https://github.com/woocommerce/woocommerce-android/pull/11249
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11316
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11317
- [x] Unit tests https://github.com/woocommerce/woocommerce-android/pull/11246
- [x] Logic to hide the card from the dashboard https://github.com/woocommerce/woocommerce-android/pull/11404
- [ ] [Dynamic Dashboard] Make stats graph span edge-to-edge (nice to have)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hichamboushaba** [comment]
Marking this as closed, the remaining task is nice to have.
