### ISSUE TITLE
[Dynamic Dashboard] New card style

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#11314]
<img width="717" alt="image" src="https://github.com/woocommerce/woocommerce-android/assets/1522856/3d8d0b6d-71c0-4531-bfa5-cb97aed04210">

All cards will have a new border and padding around them. They will all have a consistent header and button style, which includes:

- A title
- Menu button (which will add the "Hide" option to all cards)
- Optional text button at the bottom

```[tasklist]
### Tasks
- [x] New widget card style: #11325
- [x] Updated Blaze card with the new style: #11328
- [x] Updated Stats card with the new style (will be handled as part #11219)
- [x] Update Top performers card with new style  (@jorgemucientes will handle this one as part of https://github.com/woocommerce/woocommerce-android/issues/11237)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
