### ISSUE TITLE
Introduce My Store fetching logic

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11339]
When the user opens the Watch app with the Store already configured, the My Store screen should be the app's landing page. 

This task should introduce the data fetching operations to present the expected My Store data. The charts are not mandatory but are nice to have, as we're not confident about how easy it is to display this kind of data on the Watch screen.

Data fetching can be done by requesting it from the phone app or using the watch network to request it when possible.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/86a78bd2-0cec-4e96-94ad-4f7fc511b226)

```[tasklist]
### Tasks
- [x] Fetch the Orders data of the day
- [x] Update and present the orders total sales, orders count, visitors count and conversion rate
- [x] [Nice to have] Fetch the data from the watch network, when available.
- [x] Introduce Phone as data source for Stats
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
