### ISSUE TITLE
Handle Phone sync with Store credentials data

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11336]
When the user opens the WearOS app, we should be able to start a sync with the user's phone to fetch the Store Credentials.

This task should introduce wear and phone connection detection, and transfer the credential data.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/21edb2cc-e861-493c-b569-682b11670168)

```[tasklist]
### Tasks
- [x] Create the connection service to detect Watch presence in the Woo phone app
- [x] Create the connection service to detect Phone presence in the Woo watch app
- [x] Trigger the credentials transfer from Phone to Watch
- [x] Safely store the credentials data into the Watch app
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
