### ISSUE TITLE
Introduce Order list screen

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11340]
From the My Store screen, when the user clicks the `View all orders` button, we should be able to present an Order list displaying all orders from that given store.

This task should introduce the Order List UI component, allowing the user to scroll and navigate between the store order data.

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/32d5ef9a-379d-4684-85e5-cdae17afa0ac)

```[tasklist]
### Tasks
- [x] Introduce the Orders list screen with the scrollable list component
- [x] Introduce the Orders list item element with the Order data
- [x] Ensure the Order list item element displays the Order date, total, number and status
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
