### ISSUE TITLE
Introduce Order details screen

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11342]
From the Orders list screen, when the user selects one of the orders there, we should be able to present the details for that giving order.

This task should introduce the Order Details UI component, which allows the user to scroll and navigate through the order data.

Depending on the fetch strategy used in the Orders list (list summary for performance), the required data for the Order details might be limited, requiring additional data fetching. If that's not the case, close and ignore task #11343 

![Image](https://github.com/woocommerce/woocommerce-android/assets/5920403/1ee6a1d6-e204-4e60-925a-fd21b348ac4c)

```[tasklist]
### Tasks
- [x] Introduce the Order details header
- [x] Introduce the Order products list
- [ ] [Nice to have] Introduce the Order totals section (Products, Taxes, Order total, paid)
- [ ] [Nice to have] Introduce the Customer info section (Name, email, address)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
