### ISSUE TITLE
Broadcast store switching to the Watch app

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11344]
As we're not introducing a store selection option to the Watch app, whenever the user switches stores in the Woo Mobile app, we should broadcast those changes to the watch so it follows the phone configuration.

```[tasklist]
### Tasks
- [x] Verify existence/introduce listeners for Store change events
- [x] Trigger to the Watch app the credentials changes
- [x] Set the Watch to always request the current selected Store
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
