### ISSUE TITLE
Handle Error, Timeout and Credentials desync in the Wear app

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#11422]
As the authentication step main flow is done, we need to ensure some corner cases are covered, such as:

- Phone connection unavailable during first sign in
- Credentials request to Phone timeout
- App data is wiped and Credentials / site data becomes unavailable

```[tasklist]
### Tasks
- [x] React to Phone unavailability with the Login error screen
- [x] Detect when the Phone credentials request takes too long to respond with the Login error screen
- [x] Ensure the app recovers from a data wipe (if applicable)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
