### ISSUE TITLE
[Analytics Hub] Requested design enhancements

### ISSUE THREAD

**Issue by rachelmcr** [woocommerce/woocommerce-android#11429]
The following Analytics Hub design enhancements were identified in a design review after the Expanded Analytics Hub release:

```[tasklist]
### Tasks
- [ ] Fix missing charts when the Analytics Hub is first loaded
- [ ] Use Google Material symbol for edit icon
- [ ] Use Google Material symbol in data range selector
- [ ] Larger font size for analytics card titles
- [ ] Vertically align chart with badge
- [ ] 24pt gap between badge and chart
- [ ] Don’t bold the "See report" link
- [ ] Adjust analytics card vertical spacing
- [ ] Missing toolbar shadow
- [ ] You can hide all cards on Android; the final card should be disabled as on iOS
- [ ] Change red icon to grey when Sessions card can't be displayed
- [ ] Update card style to match My Store design: pe5sF9-2DL-p2#changes-to-my-store
```

![Android Review](https://github.com/woocommerce/woocommerce-android/assets/8658164/7a66e46f-9260-4331-8212-814b9166ff44)

See discussion (including link to Figma file): pe5pgL-4pB-p2#comment-3998

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Ecarrion** [comment]
@toupper I'm removing this(Together with [this one](https://github.com/woocommerce/woocommerce-ios/issues/12624)) from our backlog since we are not "responsible" of the Analytics Hub anymore.

Should we move it to Kiwi's backlog?

**Comment by toupper** [comment]
@Ecarrion Yes, let's do that, thanks for that!

**Comment by toupper** [comment]
@Ecarrion After clarification with @pmusolino Analytics will still be our responsibility, so I moved it back to our Eagle Backlog

**Comment by JorgeMucientes** [comment]
There's already an undergoing analytics audit conducted. So closing this.
