### ISSUE TITLE
[Dynamic Dashboard] Last 3 reviews card

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11474]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/pull/11477
- [ ] https://github.com/woocommerce/woocommerce-android/pull/11491
- [ ] https://github.com/woocommerce/woocommerce-android/pull/11503
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
