### ISSUE TITLE
[Payment] Testing: Add implementation so order details load successfully, emits success state and all tests pass

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11542]
Complete adding test classes and expand test cases. Make sure code coverage is increased, not decreased. See this comment:
https://github.com/woocommerce/woocommerce-android/pull/11532#issuecomment-2118303080

```[tasklist]
### Tasks
- [x] Fix unit tests
- [x] Create test plan for QA team: Ship with high quality.See iOS test plan
- [x] Make sure ChangeDueCalculatorViewModelTest has a case for all the fields in the UiState.Success class
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by backwardstruck** [comment]
Test charter: https://corvidp2.wordpress.com/2024/05/29/draft-android-cash-payment-improvements-test-charter/
