### ISSUE TITLE
[Dynamic Dashboard] Special error UI when WCAdmin is disabled and the card depends on it

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11544]
```[tasklist]
### Tasks
- [x] Make the error view reusable and update Performance card https://github.com/woocommerce/woocommerce-android/pull/11562
- [x] Integrate the error view with the coupons card https://github.com/woocommerce/woocommerce-android/pull/11562
- [ ] Integrate the error view with the products card
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
