### ISSUE TITLE
Top 3 products with low stock card

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11559]
```[tasklist]
### Tasks
- [x] Add new card displaying product stock: https://github.com/woocommerce/woocommerce-android/pull/11582
- [x] Show product sales report alongside product stock: https://github.com/woocommerce/woocommerce-android/pull/11631
- [x] Unit tests: https://github.com/woocommerce/woocommerce-android/pull/11656
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11674
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
