### ISSUE TITLE
[Payment Method Improvements] The Payment Details section should display two text fields

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11553]
This GH issue is for the Payment Details section, which should display two text fields: One text field labeled "Cash received" displaying the value given (by default the total due). One text field labeled "Change due" displaying the value "$0.00".

![IMG_9746](https://github.com/woocommerce/woocommerce-android/assets/947561/14ba209b-ea14-44d9-a265-c7463636d02f)

In addition, some follow up work from the previous [PR](https://github.com/woocommerce/woocommerce-android/pull/11532#pullrequestreview-2066531782) requested by @kidinov :

1.  make passing orderId mandatory and have compile time validation you can declare argument as part of the arguments for the fragment:
```
    <fragment
        android:id="@+id/changeDueCalculatorFragment"
        android:name="com.woocommerce.android.ui.payments.methodselection.ChangeDueCalculatorFragment"
        android:label="ChangeDueCalculatorFragment" >
        <argument
            android:name="orderId"
            app:argType="long" />
    </fragment>
```

2. then in the VM you can get the object with

private val navArgs: ChangeDueCalculatorFragmentArgs by savedStateHandle.navArgs()
navArgs.orderId

3. I noticed that you placed these calses into methodselection package which probably not the most appropriate place for that. I'd go with payments/changeduecalculator

```[tasklist]
### Tasks
- [x] make passing orderId mandatory and have compile time validation you can declare argument as part of the arguments for the fragment
- [x] in the VM you can get the object with private val navArgs: ChangeDueCalculatorFragmentArgs by savedStateHandle.navArgs() navArgs.orderId
- [x] place these calses into package  payments/changeduecalculator
- [x] UI for this creen should basically match the payment details section on iOS
- [x] Update compose previews
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
