### ISSUE TITLE
[Payment Method Improvements] tapping "Mark order as complete" button is equivalent to tapping "Mark as paid" on the current Android dialog

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11583]
```[tasklist]
### Tasks
- [x] Screen should close and return to the order screen (closing the payment method screen as well)
- [x] The order should be marked as paid/completed
- [x] Amount paid should be accurate on the order
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11592
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
