### ISSUE TITLE
[Payment Method Improvements] Implement record transaction details to order note functionality

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11585]
```[tasklist]
### Tasks
- [x] Upon returning to the order screen after marking the order as complete, there should be a note added to the order notes with the details of the cash transaction
- [x] Transaction note should contain: "The order was paid by cash. Customer paid x. The change due was x."
- [x] Deliver result correctly: https://github.com/woocommerce/woocommerce-android/pull/11587#discussion_r1617393919
- [x] Fix margin and padding: https://github.com/woocommerce/woocommerce-android/pull/11587#issuecomment-2135444695
- [x] We'd need to fix the layout for the text that displays the change: https://github.com/woocommerce/woocommerce-android/pull/11587#issuecomment-2135444695
- [x] better to make the not toggle "clickable" including the text itself and with some padding so it's easier to tap: https://github.com/woocommerce/woocommerce-android/pull/11587#issuecomment-2135444695 on:
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11604
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
