### ISSUE TITLE
[Dynamic Dashboard] Unit tests

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#11613]
```[tasklist]
### Tasks
- [x] Coupons Card https://github.com/woocommerce/woocommerce-android/pull/11618
- [x] Reviews Card https://github.com/woocommerce/woocommerce-android/pull/11626
- [x] Products Card https://github.com/woocommerce/woocommerce-android/pull/11656
- [x] Orders Card https://github.com/woocommerce/woocommerce-android/pull/11659
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
