### ISSUE TITLE
[Payment Method Improvements] Bug: Support all currency symbols correctly

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11653]
Per discussion here:
https://corvidp2.wordpress.com/2024/05/29/draft-android-cash-payment-improvements-test-charter/#comment-614

Similar to this issue that was reported on iOS:
https://github.com/woocommerce/woocommerce-ios/issues/10913

Support all the currency options from this screen:

https://woo-totally-selfless-bear.wpcomstaging.com/wp-admin/admin.php?page=wc-settings&tab=general

![Image](https://github.com/woocommerce/woocommerce-android/assets/947561/c639baf8-85a5-4acf-a43d-a1c63248c22c)

```[tasklist]
### Tasks
- [x] Support INR correctly
- [x] Support any currency symbol that displays on the right side
- [x] Support RTL currencies like the Saudi Riyal
- [x] It seems like there should be an upper limit on how many digits I can put into that field. (I didn’t hit one, so if it exists it’s very high.) Downstream of this, if the value is very high and consequently necessitates a lot of change being due, you can’t see the full value due back to the customer.
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11662
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
