### ISSUE TITLE
[Woo POS] Totals view

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11694]
Based on this iOS issues:
https://github.com/woocommerce/woocommerce-ios/issues/12763 and
https://github.com/woocommerce/woocommerce-ios/issues/12983

"After tapping in checkout, we'll have a "Totals" view with some sort of accumulated data and the payment buttons"
```[tasklist]
### Tasks
- [x] Add Totals view first: https://github.com/woocommerce/woocommerce-ios/pull/12809
- [x] Make PR similar to this: https://github.com/woocommerce/woocommerce-ios/pull/12850
- [x] Pass an order ID from the cart to the totals: https://github.com/woocommerce/woocommerce-android/pull/11717
- [x] Get it from DB
- [x] Map to UI state
- [x] Display totals and tax (without mastering UI at this time)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
