### ISSUE TITLE
[Woo POS] Correctly Display Sub-Amounts (Subtotal, Taxes, etc.) on Totals Screen

### ISSUE THREAD

**Issue by backwardstruck** [woocommerce/woocommerce-android#11692]
Develop the logic to calculate and show subtotals, taxes, and other sub-amounts.

Figma:

![Image](https://github.com/woocommerce/woocommerce-android/assets/947561/57834513-f90f-4e5e-9891-40a60656e60a)

```[tasklist]
### Tasks
- [x] Implemented a temporary totals calculation: A fixed 10% tax is calculated on the subtotal. The total amount is calculated by adding the subtotal and tax.
- [x] While totals are being calculated, a shimmering effect is displayed on the labels for the prices. See: https://github.com/woocommerce/woocommerce-android/pull/11821
- [x] If the total amount is not pre-calculated, users see a “Calculate amounts” button to trigger the calculation.
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
