### ISSUE TITLE
[Woo POS] Using selected products create an order draft

### ISSUE THREAD

**Issue by kidinov** [woocommerce/woocommerce-android#11704]
Branch of [this](https://github.com/woocommerce/woocommerce-android/pull/11699) PR from @samiuelson

From [this](https://a8c.slack.com/archives/C06C3CZFHGD/p1717769577752619) discussion in Slack:

- Create an order
- Add products to it
- Order model is returned
- It will contain everything we need
- IF there are any modifications to the cart, we add to the order

```[tasklist]
### Tasks
- [x] Update ViewModel for Order Creation
- [x] get products
- [x] Put into the model
- [x] Handling API Integration
- [x] do the request to create order upon tapping the checkout button
- [ ] Reuse existing code
- [ ] Update UI and View States
- [ ] Testing
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
