### ISSUE TITLE
Update Order when a new order notification arrives

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#11794]
# Task

- [ ] Fetch & store the order of a notification when it arrives while the app is killed or in the background
- [ ] Update the order list too. 
- [ ] Make sure the last updated timestamp is updated.

## Notes:

iOS works like:

- Get push notification
- Sync notification object
- If the notification is an store order notification
    - Sync the order list (with filters)
    - If the notification order did not come in the order list, Sync the notification order.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
