### ISSUE TITLE
Product Creation with AI: v2 - Milestone 1

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11800]
Version 1 - https://github.com/woocommerce/woocommerce-ios/issues/10688
Design - pe5sF9-2Nd-p2
Internal - pffQ75-yr-p2
Cloned from iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/13103

```[tasklist]
### Ai product prompt screen
- [ ] #11849
- [ ] #11899
- [ ] #11909
- [ ] #11878
- [x] Add tone selector to the new main screen -> Done as part of https://github.com/woocommerce/woocommerce-android/issues/11878
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12065
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12086
```

```[tasklist]
### Ai product preview screen
- [ ] #11927
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12007
- [ ] #11954
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12004
- [ ] #11972
- [ ] #11973
- [ ] #11996
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11929
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11930
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12021
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12101
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12025
```

```[tasklist]
### Miscellanea
- [ ] #11802
- [ ] #11848
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12054
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12063
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12367
- [x] https://github.com/woocommerce/woocommerce-android/issues/12368
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
