### ISSUE TITLE
Product Creation with AI: v2 - Milestone 2

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11859]
Milestone 1 - #11800 
Design - pe5sF9-2Nd-p2
Internal - pffQ75-yr-p2

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/13117

### Feature flag
- [ ] Add feature flag

#### Details
- [ ] Make "Price" field editable.
- [ ] Make "Inventory" field editable.
- [ ] Make "Categories" field editable.
- [ ] Make "Tags" field editable.
- [ ] Make "Shipping" field editable.

#### General updates
- [ ] "Publish" button and action

### Tracking
- [ ] Define tracking events. (If needed, create test funnels to ensure project success can be measured.)
- [ ] Add tracking events.

### Release
- [ ] Add release notes and enable feature flag.
- [ ] Remove the feature flag.

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.

**Comment by JorgeMucientes** [comment]
Duplicated from here: https://github.com/woocommerce/woocommerce-android/issues/11860
