### ISSUE TITLE
Product Creation with AI: v2 - Milestone 3

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#11860]
Milestone 2 - #11859 
Design - pe5sF9-2Nd-p2
Internal - pffQ75-yr-p2

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/13118

```[tasklist]
### Tasks
- [x] https://github.com/woocommerce/woocommerce-android/issues/12051
- [x] UI - Progress bar and label with dynamic color and text. Done as part of https://github.com/woocommerce/woocommerce-android/issues/11862
- [x] https://github.com/woocommerce/woocommerce-android/issues/11862
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12102
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12128
```

```[tasklist]
### Release
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12131
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12245
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
