### ISSUE TITLE
[Login] Add support for signing in to Black-flagged Sites

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#12031]
## Description
When users attempt to log into the app with a black-flagged site URL, they receive an error message stating the URL is invalid and are unable to proceed with login.

This task should update the login flow to gracefully handle this case by directing those users to use site credentials instead of WordPress.com.

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12775
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12779
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12782
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12789
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12790
```

## References
peaMlT-JX-p2
https://github.com/woocommerce/woocommerce-ios/issues/13348

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
