### ISSUE TITLE
Automated Smoke Tests for Core Functionalities

### ISSUE THREAD

**Issue by pmusolino** [woocommerce/woocommerce-android#12168]
Enhance the test coverage by including tests for edge cases, particularly focusing on the visibility of core functionalities under different conditions. This initiative requires identifying all relevant cases and logging the entry points that should be tested. 
More context: p91TBi-bKp#comment-12649

iOS issue: https://github.com/woocommerce/woocommerce-ios/issues/13453

#### Tasks:
   - Identify extra edge cases for visibility of core functionalities.
   - Log the entry points that need to be tested.
   - Ensure all relevant scenarios are covered.
   - Although UI tests are currently flaky and used mainly for generating automated screenshots, they could be improved to cover these edge cases more reliably.

- [ ] **My store tab visibility**
   - [ ] Edit Dynamic Dashboard flow
   - [ ] Onboarding: View all tasks
   - [ ] Onboarding: View the next task
   - [ ] Performance: View All Store Analytics
   - [ ] Performance: edit custom range
   - [ ] Top Performers: View all store analytics
   - [ ] Top Performers: edit custom range
   - [ ] Blaze: Create campaign
   - [ ] Blaze: Open campaign detail
   - [ ] Blaze: View all campaigns
   - [ ] Google Ads Campaigns: Open campaign detail
   - [ ] Google Ads campaigns: Create campaigns
   - [ ] Google Ads campaigns: View All campaigns
   - [ ] Inbox: View All messages
   - [ ] Reviews: View all reviews
   - [ ] Reviews: Open review detail
   - [ ] Coupons: View all coupons
   - [ ] Coupons: open coupon detail
   - [ ] Stock: open product detail
   - [ ] Most recent orders: Open order detail
   - [ ] Most recent orders: View all orders
- [ ] **Orders visibility**
   - [ ] Scan barcode
   - [ ] Search
   - [ ] Add new order
   - [ ] Filter
   - [ ] Order Details
     - [ ] Edit Order
     - [ ] Add customer note
     - [ ] Collect payment
     - [ ] View custom fields
     - [ ] Order status
     - [ ] Edit Shipping address
     - [ ] Add a note
     - [ ] Open products
   - [ ] Open filters
     - [ ] Order Status
     - [ ] Date Range
     - [ ] Customer
     - [ ] Product
- [ ] **Product visibility**
   - [ ] Scan product
   - [ ] New product
   - [ ] Search
   - [ ] Bulk update
   - [ ] Sort by
   - [ ] Filters
   - [ ] Product detail
    - [ ] Images
    - [ ] Description
    - [ ] Write with AI
    - [ ] Promote with Blaze
    - [ ] Price
    - [ ] Reviews
    - [ ] Inventory
    - [ ] Categories
    - [ ] Downloadable files
    - [ ] Product type
    - [ ] Add more details
    - [ ] Tags
    - [ ] Short Description
    - [ ] Linked products
    - [ ] Settings
    - [ ] Status
      - [ ] Visibility
      - [ ] Catalog Visibility
      - [ ] Virtual product
      - [ ] Downloadable product
      - [ ] Enable reviews
      - [ ] Slug
      - [ ] Purchase note
      - [ ] Menu order
- [ ] **Menu**
   - [ ] Change Store
   - [ ] Settings
   - [ ] Domains
     - [ ] Plugins
     - [ ] WooCommerce version
     - [ ] Store Name
     - [ ] Themes
     - [ ] Help & support
     - [ ] Experimental features
     - [ ] Send Feedback
     - [ ] Privacy Settings
     - [ ] WooCommerce
     - [ ] What’s New in WooCommerce
     - [ ] Open Device Settings
     - [ ] Account Settings
     - [ ] Log out
   - [ ] Subscriptions
   - [ ] Payments
   - [ ] Google for WooCommerce
   - [ ] Blaze
   - [ ] WooCommerce Admin
   - [ ] View Store
   - [ ] Coupons
   - [ ] Reviews
     - [ ] Review Detail
       - [ ] Spam
       - [ ] Trash
       - [ ] Approved
       - [ ] Reply
       - [ ] Share
   - [ ] Inbox
   - [ ] Customers
     - [ ] Search bar
     - [ ] Customer detail

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
