### ISSUE TITLE
[Wear App] Add Sentry support

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#12225]
# Summary

After the recent events with the Wear app crash detected in the Play Store console, the need for Sentry adoption in the Wear app became high priority. 

The WCAndroid code base approaches Sentry support through the Automattic-Tracks-Android library, which is directly imported into the app dependencies. This library works by linking the FluxC account and storing data with the app context through the CrashLoggingDataProvider interface delegated by the SentryCrashLogging . We can see this happening in the WCCrashLoggingDataProvider class.

# Solution
Pocket Casts uses a build-time tag to differentiate Mobile from [Wear crashes](https://href.li/?https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/crashlogging/src/main/java/au/com/shiftyjelly/pocketcasts/crashlogging/PocketCastsCrashLoggingDataProvider.kt#L31) alongside a modular strategy to allow the Crash Logging logic available to both Wear and Mobile apps. We can use something similar for WCAndroid, coupling the Wear app reports to the same Mobile project.

However, since we don’t have a fully modular architecture in the WCAndroid project, we can resort to the commons module that’s used for declaring code used by both Mobile and Wear modules. The solution start point is moving the CrashLogging code to that module.

```[tasklist]
### Tasks
- [x] Introduce the Automattic-Tracks-Android to the commons module https://github.com/woocommerce/woocommerce-android/pull/12233
- [x] Create the Wear counterpart of the `WCCrashLoggingDataProvider` class https://github.com/woocommerce/woocommerce-android/pull/12233
- [x] Support sending Settings from the Phone to the Wear https://github.com/woocommerce/woocommerce-android/pull/12280
- [x] Prepare the WCAndroid Sentry project with the Wear connection https://github.com/woocommerce/woocommerce-android/pull/12313
- [x] Test both Mobile and Wear reports are working as expected
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
