### ISSUE TITLE
[Blaze i4] New Objective section

### ISSUE THREAD

**Issue by irfano** [woocommerce/woocommerce-android#12469]
```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/pull/12616
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12660
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12661
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12706
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12742
- [ ] https://github.com/woocommerce/woocommerce-android/pull/12796
- [ ] https://github.com/woocommerce/woocommerce-android/pull/12795
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
