### ISSUE TITLE
Blaze iteration 4

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#12538]
```[tasklist]
### Milestone 1
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12146
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12188
```

```[tasklist]
### Milestone 2
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12176
```

```[tasklist]
### Milestone 3
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12469
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12750
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12494
- [ ] https://github.com/woocommerce/woocommerce-android/issues/11323
- [ ] https://github.com/woocommerce/woocommerce-android/issues/12547
```

**Comment by dangermattic** [comment]
🚫 Please add a type label (e.g. **type: enhancement**) and a feature label (e.g. **feature: stats**) to this issue.
