### ISSUE TITLE
Support hiding websites from the site picker

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#13107]
###### iOS counterpart: https://github.com/woocommerce/woocommerce-ios/issues/14658

The app currently lists all Woo Stores connected to the user's WordPress.com account, which can clutter the screen for agencies and site builders when client stores are also connected.

![Image](https://github.com/user-attachments/assets/645330d1-e010-4d9d-b48f-591fff0d7ef8)

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/13108
- [ ] https://github.com/woocommerce/woocommerce-android/issues/13127
- [ ] https://github.com/woocommerce/woocommerce-android/issues/13136
- [ ] https://github.com/woocommerce/woocommerce-android/issues/13163
- [ ] https://github.com/woocommerce/woocommerce-android/issues/13213
- [ ] https://github.com/woocommerce/woocommerce-android/issues/13222
- [ ] https://github.com/woocommerce/woocommerce-android/issues/13159
- [ ] https://github.com/woocommerce/woocommerce-android/issues/13267
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
