### ISSUE TITLE
Hack Week: Convert Order List to use new list management backend

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1330]
Convert the order list tab to use the new order list management implemented in FluxC.

## TODO

- [x] Basic list conversion and MVVM conversion (#1496 ) 
- [x] Hide future orders (#1497, [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1410), #1510)
- [x] Offline handling (#1495, PR #1513, [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1412))
- [x] Error, Loading & Empty States (#1514, PR #1530, [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1419))
- [x] Fix tests (#1533, PR #1538  )

**Comment by JavonDavis** [comment]
Hey! I'm bumping this to `3.2`, but if all the tasks are good to go we can go ahead and close this. If there's more work on it you'd like to get it in for this release please merge this into release/3.1 and then DM me to release a new Beta version.`

**Comment by AmandaRiu** [comment]
Thanks @JavonDavis , I think this will have to wait for the next release. It is good to go now, but there is another PR in the pipeline that will create significant changes to the logic in this PR so once that one merged this will will need to be updated again with some new logic.
