### ISSUE TITLE
Order List redesign - Master checklist

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1398]
This is the master epic for the changes required to accomplish the order list improvements.

#### Changes in FluxC:
- [x] [#1372](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1372) - Cache the total order status count from the order status total api response (PR: [#1376](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1376), [#1389](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1389))

#### UI Changes:
- [x] #1399 - Add `TabLayout` to the order list UI: `Processing` and `All Orders` (PR: #1404 )
   - [x] Anchor the `TabLayout` when the view is scrolled.
   - [x] Remember the `Tab` selected and default to that tab. Default is `Processing`.
- [ ] #1411 - Handle empty state scenarios in order list (PR: #1430)
- [x] #1400 - Enhance search support to the order list UI (PR: #1428)
   - [x] Remove the filter option from the toolbar menu
   - [x] Add new search UI that displays list of order statuses along with their count.
   - [x] Clicking on an order status from the above UI will display the list of orders for that status.

<img width="300" src="https://user-images.githubusercontent.com/22608780/63924685-5438e300-ca66-11e9-92b3-f57675d56698.png"> . <img width="300" src="https://user-images.githubusercontent.com/22608780/63924665-47b48a80-ca66-11e9-8540-9da91da1cab2.png">
