### ISSUE TITLE
Order Products Card - Add Fulfill/Details Button views

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#141]
Add support for different view states depending on the status of the order, and the screen this card is being displayed on. 

**Collapsed View**
* Display a collapsed list of products: 

![screen shot 2018-05-04 at 3 25 35 pm](https://user-images.githubusercontent.com/5810477/39653765-8183e19e-4faf-11e8-9a0f-f9682760b54d.png) ![screen shot 2018-05-04 at 2 49 04 pm](https://user-images.githubusercontent.com/5810477/39652459-dc72afcc-4faa-11e8-8602-1f0599f667fc.png)

**Expanded View**
* Display the expAnded list of products
* Hide any buttons when in the Order Fulfillment View

![screen shot 2018-05-04 at 3 27 19 pm](https://user-images.githubusercontent.com/5810477/39653815-a9faad2e-4faf-11e8-8dcc-1f7ef63a14d1.png)

**Order Fulfillment Button**
* Only displayed when in the Order Details view and the order status **is** `processing`
* Clicking this button will open the Order Fulfillment Page

![screen shot 2018-05-04 at 2 49 04 pm](https://user-images.githubusercontent.com/5810477/39652459-dc72afcc-4faa-11e8-8602-1f0599f667fc.png)

**Details Button**
* Only displayed when in the Order Details view and the order status **IS NOT** `processing`
* Clicking this button will show the expanded products view

![screen shot 2018-05-04 at 3 25 35 pm](https://user-images.githubusercontent.com/5810477/39653765-8183e19e-4faf-11e8-9a0f-f9682760b54d.png)

## TODO
- [x] Add a collapsed (simplified) products view and the ability to easily switch between them programmatically
- [x] Add `FULFILL ORDER` button -> Visible only if order status is "processing"
		- Opens a new view for order fulfillment
- [x] Add `DETAILS` Button -> visible only if order status is NOT "processing"
		- Show the expanded products view.
		- Change button text to `HIDE DETAILS`
- [x] If order complete, hide `Fulfill Order` button and show a `Details` button instead. 
- [x] Ability to hide both buttons programmatically
