### ISSUE TITLE
Jetpack sign-in with self-hosted credentials - Master checklist

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1482]
This is the master epic for the changes required to accomplish jetpack sign-in with self-hosted credentials.

#### Changes in FluxC:
- [#1402](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1402) - Fetch `jetpack_user_email` param from from the `xmlrpc wp.getOptions` endpoint and cache locally. (PR: [#1403](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1403)) 

#### Changes in Login library:
- [x] Step 1: Fetch Jetpack e-mail address for flowing through Magic Links: (PR: #1483 )
  - [x] Revert existing logic of validating site url from `FETCH_CONNECT_SITE_INFO` endpoint and use the `FETCH_WPCOM_SITE_BY_URL` endpoint and initiate the discovery process.
  - [x] Add new button to email screen to `Login via site credentials`.
  - [x] When site credentials are clicked:
     - [x] If jetpack is installed/active/connected: call the `wp.getOptions` endpoint to fetch the `jetpack_user_email` and store in `SiteModel` and rRedirect to the request magic link screen.
     - [x] If jetpack NOT installed/active/connected: Redirect to Jetpack required screen.
- [x] Step 2: Initiate verification email for the jetpack connected email address. (PR: #1498 )
- [ ] Step 3: Add Track events for the new buttons/views.
- [x] Step 4: Handle discovery error scenarios for Woo. (PR: #1515 )
     - [x] This includes creating a base class that handles the discovery process and provides an option for the calling class to handle the errors as they see fit.
     - [x] One of the tasks include porting over changes from the `LoginSiteAddressFragment` to utilise this base class.

![Screenshot on 2019-10-21 at 14_27_17](https://user-images.githubusercontent.com/22608780/67191219-e62dee00-f40e-11e9-9c22-242a52b9c53c.png)
