### ISSUE TITLE
Dark Mode: style order detail screens

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#1587]
Implement light/dark mode on the order detail screen. 

## Todo
- [x] Order Status card (#1919)
- [x] Products card (#1922)
- [x] Payment Card (#1932)
- [x] Customer Information Card (#1933)
- [x] Notes card (#1934)
- [x] Shipping Method notice card (#1964)
- [x] Change order status dialog (#1965)
- [x] Refunded Products card (#1963)
- [x] Shipment Tracking card (#1963)
