### ISSUE TITLE
Add/Edit Product Release 1: Update product description Master checklist 

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1594]
This is the checklist for the changes required to update product description.

#### Changes in FluxC:
- [x] [#1431](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1431) - Add methods to update a product. (PR: [#1432](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1432)) 

#### Changes in Woo:
- [x] Add aztec editor to Woo without media support. (PR: #1553)
- [x] Add option to display images in Aztec editor. (PR: #1605)
- [x] Add Publish/Update button to Product Detail screen and update product. (PR: #1613)
- [x] Add track events to the product update feature. (PR: #1638)

**Comment by AmandaRiu** [comment]
Moving to milestone 3.4. If this needs to go into 3.3, please submit a hotfix targeting the `release/3.3` branch.
