### ISSUE TITLE
Add/Edit Product Release 1: Update product inventory

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#1614]
Add support for displaying/updating product inventory.

<img width="615" alt="Screenshot 2019-11-29 at 1 16 21 PM" src="https://user-images.githubusercontent.com/22608780/69852509-72eb8780-12aa-11ea-8a6a-a2fb25654c78.png">

#### Master Checklist
- [x] Display new designs for product inventory + pricing (PR: #1810 )
- [x] Display new inventory editing screen (PR: #1811 )
- [x] Add logic to verify if SKU exists for a product when SKU is changed. (PR: #1870 )
- [x] Add logic to update product inventory details (PR: #1887 )

**Comment by AmandaRiu** [comment]
Moving to milestone 3.4. If this needs to go into 3.3, please submit a hotfix targeting the `release/3.3` branch.

**Comment by anitaa1990** [comment]
Closed via #1810, #1811 , #1870 , #1887
