### ISSUE TITLE
Offline Status Design and Handling

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#199]
Add network connectivity monitoring and notification system. 

<img width="389" alt="screen shot 2018-08-11 at 9 25 56 pm" src="https://user-images.githubusercontent.com/5810477/43997853-3059a1fe-9dad-11e8-8204-06b0c5dc7d50.png">

**TODO:**
- [x] Create new sticky notification message bar for displaying at the activity level
- [x] Add to current activities where it makes sense. These activities should check for connectivity in onResume().
- [x] Add a way to listen for network changes - hide/show bar when changed
- [x] Update any views requesting something that requires a network to do a network check first and if no network, either return cached data or exit (where cached data is currently supported)
- [x] All action-type buttons that require network connectivity should show a "not connected" toast when pressed.
- [x] Add offline bar animation
- [x] Unit tests
