### ISSUE TITLE
Update order stats styling

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#261]
Update the order stats card to latest design:

<img width="372" alt="screen shot 2018-06-20 at 9 01 11 am" src="https://user-images.githubusercontent.com/9613966/41660015-d6880390-7468-11e8-8d23-cf271406f33e.png">

* [x] Only show first and last date on x-axis (done in #274)
* [x] Replace y-axis with two currency limit lines (done in #347)
* [x] Add "Updated ..." label at the bottom (done in #321)
* [x] In `Days` view, color weekend days gray (done in #347)
* [x] Format revenue total and y-axis currency values with `k` values when appropriate, and correctly localize (also relates to #148)

**Comment by AmandaRiu** [comment]
All items finished and merged. Closing.
