### ISSUE TITLE
Dashboard: Orders to fulfill

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#283]
As a store owner I want a quick way to see how many open orders I have, and have a quick way to go directly to a list of them.

![dashboard-orders-to-fulfill](https://user-images.githubusercontent.com/9613966/42824819-a4299174-89ae-11e8-8a27-edf96f43e506.png)

Relies on https://github.com/woocommerce/woocommerce-android/issues/282, so we can open the order list filtered to 'Processing' orders.

## TODO

**FluxC**
- [x] Fetch orders filtered by the order status "processing" - these would not be saved in the database, but instead used just to grab a count. We don't want to save these changes in the database because the orders view may currently be filtered by something entirely different and the database is currently refreshed after every filter change.

**UI**
- [x] On first load or force refresh of dashboard, grab total count from FluxC
- [x] Create a new view (not generic, we'll convert it later if variations are needed)
- [x] Add view to dashboard, visible only if there are orders waiting for fulfillment
- [x] Add click event to open the orders view filtered by "processing"
-- this should always force a refresh of the data, even if the view is already filtered by orders.
- [x] Refresh dashboard on initial load and then anytime an onOrderChanged event that is NOT the event to fetch order count is fired (deferred refresh if dashboard not active)
- [x] Add unit tests for any Dashboard contract changes
