### ISSUE TITLE
Hack Week: Refactor Order detail screen from MVP to MVVM

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#2844]
This is the master thread to track the progress of converting the Order detail screen from MVP to MVVM.

#### FluxC:
- [x] Remove redundant `WCOrderModel` when fetching order notes. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant `WCOrderModel` when fetching order shipment trackings. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant WCOrderModel when updating order status. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant WCOrderModel when adding order note. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant WCOrderModel when adding new shipment tracking. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))
- [x] Remove redundant WCOrderModel when deleting new shipment tracking. (PR: [#1689](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1689))

##### Order Detail Sections:
- [x] Display **Order Status Info** card. (PR: #2856 )
- [x] Display **Shipping Lines Warning** card, if order has more than 1 shipping methods. (PR: #2857 )
- [x] Display **Customer Info** card - Shipping/Billing address. (PR: #2860 )
- [x] Display **Payment Info** card. (PR: #2861 )
- [x] Display **Order notes** card. (PR: #2866 )
- [x] Display **Refunds Info** card. (PR: #2871 )
- [x] Display **Product List** card. (PR: #2872  )
- [x] Display **Shipment Tracking list** card, if WCS plugin is available. (PR: #2873  )
- [x] Display **Shipping Labels** card, if WCS plugin is available. (PR: #2874 )

##### Order Detail Actions:
- [x] Add Pull to refresh action to the Order Detail screen. (PR: #2875  )
- [x] Change Order Status (PR: #2875 )
- [x] Fulfill Order  (PR: #2878  )
- [x] Issue Refund. (Open Issue Refund screen and update the Order Detail when refund is successful).
- [x] Open Refund detail screen. (PR: #2875 )
- [x] Send email using billing email. Call/message billing phone number. (PR: #2875 )
- [x] Add new order note. (Open Add order note screen and update the Order Detail when successful). (PR: #2876  )
- [x] Request Refund for a shipping label. (PR: #2876  )
- [x] Add Shipment Tracking for an order.  (PR: #2877  )
- [x] Delete Shipment Tracking for an order.  (PR: #2877  )
- [x] Track/Copy Tracking number for an order (with WCS or Shipment Tracking plugin enabled).  (PR: #2877  )

#### Testing
- [x] Add unit tests for `OrderDetailViewModel`.  (PR: #2878  )
