### ISSUE TITLE
Add Tracking for Downloadable Files and Enable it for All

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#3353]
### Detail Page

<img src="https://user-images.githubusercontent.com/198826/102689914-1746b180-41bf-11eb-9f77-02743290b601.png" width="300">

- [x] When the Downloadable files button is tapped, trigger the event `product_detail_view_downloadable_files_tapped`.

### Settings

<img src="https://user-images.githubusercontent.com/198826/102690386-414da300-41c2-11eb-8784-7bbe427c7c96.png" width="300">

- [x] When tapping Done, trigger the event `product_downloadable_files_settings_changed`. 

### Downloadable File Item

<img src="https://user-images.githubusercontent.com/198826/102690567-88886380-41c3-11eb-8bc2-5969993ded60.png" width="250"><img src="https://user-images.githubusercontent.com/198826/102690449-c042db80-41c2-11eb-877d-c1b13e51e527.png" width="250"><img src="https://user-images.githubusercontent.com/198826/102690536-524ae400-41c3-11eb-8108-0b00656ac3d9.png" width="250">

- [x]  When modifying downloadable files, trigger these events:

Event Name | Trigger | Custom Properties
--------|-------|----
`products_downloadable_file`        |  When tapping Done in the Add downloadable file screen.      |  `action="added"`
`products_downloadable_file`        |  When tapping Update for an existing downloadable file.      |  `action="updated"`
`products_downloadable_file`        |  After confirming the deletion of a downloadable file.      |  `action="deleted"`

## Enable for All

- [x]  The Downloadable Files feature should no longer be hidden under the M5 feature flag.

---

iOS: https://github.com/woocommerce/woocommerce-ios/issues/3381
