### ISSUE TITLE
Notifications: Mark I

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#36]
As a store owner I want to get a notification every time an order comes in, so I can review the order details, and maybe fulfill.

From MVLP discussion: Similar to the WP apps provide a way of seeing WC-related notes. Try and filter out notes that aren’t appropriate for the app (Likes, Comments, etc) but still show things like Jetpack site down, new orders, out of stock, etc.

**Notifications UI: List and Detail**
- [x] Display a list of notifications #39 
- [x] Display product review detail #37 
- [x] Open new order notification in order detail view #518 
- [x] Add Tracks events #568
- [x] Mark notification as read #587

**Push Notifications**
- [x] Push Notifications #501 
- [x] Connect push notifications to notifications UI #579
