### ISSUE TITLE
Update illustrations in the app

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#3657]
_Shamelessly copied from iOS: woocommerce/woocommerce-ios#3786_

Ref: G's post p91TBi-40j-p2

Let's update the illustrations in the app to the latest design from Core!

## Orders tab

- [x] Processing tab empty state #3678 
- [x] All Orders tab empty state #3678
- [x] Search results empty state #3678
- [x] Filtered orders empty state #3678

## Products tab

- [x] Products tab empty state #3678
- [ ] Product couldn't be loaded empty stat
- [ ] Product has been deleted empty state

## Reviews tab

- [x] Reviews tab empty state #3678

## Shipping labels

- [ ] Shipping label printing instructions screen 

## Sign in

- [ ] Invalid site error screen
- [ ] Invalid account error screen
- [ ] "What is Jetpack" modal
- [x] Jetpack not connected screen #3678

**Comment by anitaa1990** [comment]
This is released in v6.8 so closing this one
