### ISSUE TITLE
Notification detail view

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#37]
Show a detailed view of a notification calling out any important things specifically for a ~new order~ review notification.

<img width="1092" alt="screen shot 2018-11-06 at 4 56 21 pm" src="https://user-images.githubusercontent.com/5810477/48294065-2db2a880-e450-11e8-8ced-1c932667b95f.png">

<img width="300" alt="screen shot 2018-11-06 at 4 56 08 pm" src="https://user-images.githubusercontent.com/5810477/48294066-30ad9900-e450-11e8-9eeb-2f6f32cb2e9c.png">

## TODO
- [x] Add Review Detail View
- [x] Add Review skeleton loading #517 
- [x] Hook into FluxC for real data
- [x] Add actions logic for approve/unapprove, spam, trash

## SPECIAL NOTE:
The following was noted on the iOS side, so for now don't show errors around product review moderation (https://github.com/woocommerce/woocommerce-ios/issues/470):

As part of the work [in iOS], @jleandroperez and I discovered that even though a comment is successfully moderated as Spam/Trash (as verified on the web), the server can still return an error:
```
{
    "code": 404,
    "headers": [
        {
            "name": "Content-Type",
            "value": "application/json"
        }
    ],
    "body": {
        "error": "unknown_comment",
        "message": "Unknown comment"
    }
}
```
Not sure right now the best approach to handle this. For now, we decided to comment out the error notices (here and here) so the beta testers don't file a flood of bug reports.

These notices should be un-commented once a solution is found.
