### ISSUE TITLE
Notifications list

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#39]
Add notifications list to the notifications tab. This includes the following:
- Loading skeleton
- List with custom notification list items for review and order notifications.
- Toolbar menu item to mark all notifications as read.

[note: the design screenshot below shows different filtering items, but these will not be implemented as of the latest i6 design comments.]

## Loading
<img width="275" alt="screen shot 2018-10-29 at 4 49 40 pm" src="https://user-images.githubusercontent.com/5810477/47681005-c0289180-db9e-11e8-8647-dfaeac024b07.png"> 

## Loaded List
<img width="275" alt="screen shot 2018-10-29 at 4 49 18 pm" src="https://user-images.githubusercontent.com/5810477/47680876-78a20580-db9e-11e8-9b48-fef5f2ce7aec.png">

## TODO
- [x] Custom Notification List Items and list view #465 
- [x] List loading skeleton #483 
- [x] Hook into FluxC for real data #546 
- [x] Open 'New Order' notifications in the Order Detail View #518 
- [x] Open `Product Review` notifications into a detail view #37
