### ISSUE TITLE
[Card Present Payments] Accept payments - Out of Beta scope 

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#4030]
This is a follow up of https://github.com/woocommerce/woocommerce-android/issues/3726. It contains all remaining tasks required for the MVP.

Latests designs as of 3/22/21 (note the flow will be slightly different for "scheduled delivery")
![image](https://user-images.githubusercontent.com/2261188/112050136-20288580-8b16-11eb-82ee-291c8f9c59b2.png)

- [x] Add the first set of metadata to PaymentIntent (customer name, email, order) (PR https://github.com/woocommerce/woocommerce-android/pull/4467)
- [x] Add order_key to PaymentIntent's metadata (@AnirudhBhat )
- [x] Play cha-ching sound when the payment succeeds (@nbradbury)
- [x] Include cart content (https://github.com/woocommerce/woocommerce-ios/issues/4297 more info p91TBi-5ej-p2)
- [x] To create and pass along a WCPay (Stripe) Customer ID: (https://github.com/woocommerce/woocommerce-ios/issues/4298 https://github.com/woocommerce/woocommerce-ios/issues/4299 https://github.com/woocommerce/woocommerce-ios/issues/4300. Proposed API: https://github.com/Automattic/woocommerce-payments/issues/1918
More info p91TBi-5ej-p2)
- [x] Cancel the payment intent when the user cancels the flow (PR https://github.com/woocommerce/woocommerce-android/pull/4402#issuecomment-878258226) 
- [x] Cancel all cancellables when the flow gets canceled
- [x] Check if we can disable Google Pay when collecting payment - maybe [this](https://stackoverflow.com/questions/47696814/can-android-pay-be-disabled-in-app), but I'm afraid we'll need yet another permissions for it :(
- [x] Introduce "create stripe customer" endpoint in WCPayStore and invoke it from the app (see p91TBi-4VZ-p2)
- [ ] ~Hide "Send receipt" and display "A receipt has been emailed to blahblah@blah.com" when billingEmail is not empty (needs design)~ (moved into [a separate ticket](https://github.com/woocommerce/woocommerce-android/issues/5967))
BackLog:
- [ ] ~Add support for non-US orders~ (out of scope)
- [ ] ~Add support for reoccurring payments~ (out of scope) https://github.com/woocommerce/woocommerce-android/issues/3830
