### ISSUE TITLE
Migrate to v3 REST API

### ISSUE THREAD

**Issue by bummytime** [woocommerce/woocommerce-android#414]
For MVLP, we are only going to support the [v3 REST API](https://github.com/woocommerce/woocommerce/tree/master/includes/api) which is shipping in WooCommerce 3.5. In order to adopt it, we will need to make a few modifications:

Step 1 (release X):
- [x] Review all of the v2 endpoints we currently consume and make sure there aren't any big blockers
- [x] If a WooCommerce v3.4 or older user is already logged into the beta app, display a warning dialog to them -> #521 (and https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/990)

Step 2 (release X+1):
- [x] Upgrade all v2 endpoints to v3, making any changes as needed (probably includes #206) -> #523
- [x] If possible, filter the site picker during auth to only display v3.5+ sites (otherwise interrogate the site upon user-selection and display warning if it's not a v3.5 site) (tracked in https://github.com/woocommerce/woocommerce-android/issues/469) -> #535 
- [x] If a WooCommerce v3.4 or older user is already logged into the beta app, update the warning dialog to explain why things are broken -> #524

WCiOS issue: https://github.com/woocommerce/woocommerce-ios/issues/352

/cc @aforcier
