### ISSUE TITLE
Product Details: Change "Update" to "Save"

### ISSUE THREAD

**Issue by shiki** [woocommerce/woocommerce-android#4362]
Ref p91TBi-5oi-p2#comment-5224.

When changes are made on a draft product, the app shows "Update" at the top right. This should be changed to "Save" to match iOS.

![image](https://user-images.githubusercontent.com/198826/124511526-997d7880-dd93-11eb-9830-d53364407d9e.png)

The progress message should be changed to “Saving your product”

<img src="https://user-images.githubusercontent.com/198826/124511766-232d4600-dd94-11eb-95eb-0f5bf71e0b82.png" width="300">

The confirmation message should be changed to "Product saved":

<img src="https://user-images.githubusercontent.com/198826/124511669-ed885d00-dd93-11eb-845e-9799925309bd.png" width="300">

## Tasks 

- [ ] Rename "Update" to "Save"
- [ ] Update progress message
- [ ] Update confirmation message

---

Related: https://github.com/woocommerce/woocommerce-android/issues/4361
