### ISSUE TITLE
CPP Onboarding: Epic Phase 1

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#4413]
Provide merchants with information about the next necessary step they need to take in order to enable in-person payments on their stores.

Designs are available on vaw3DvewbUwuQnPXpdNGGH-fi-370%3A468 - **we should consider implementing any deviations from the scope (p91TBi-5uD-p2) in the next phase of this project.**

Eligibility Checks
- [x] Introduce a feature flag (PR https://github.com/woocommerce/woocommerce-android/pull/4415)
- [x] Create initial structure (PR https://github.com/woocommerce/woocommerce-android/pull/4417 )
- [x] Loading state UI 
- [x] Unsupported country state UI
- [x] Unsupported country state business logic
- [x] WCPay not installed state UI
- [x] WCPay not installed state business logic
- [x] WCPay not activated state UI
- [x] WCPay not activated state business logic
- [x] Unsupported WCPay version state UI
- [x] Unsupported WCPay version state business logic
- [x] WCPay not setup state UI
- [x] WCPay not setup state business logic
- [x] Stripe Account Restricted – Under Review state UI
- [x] Stripe Account Restricted – Under Review state business logic
- [x] Stripe Account Restricted – Pending Requirements state UI
- [x] Stripe Account Restricted – Pending Requirements state business logic
- [x] Stripe Account Restricted – Overdue Requirements state UI
- [x] Stripe Account Restricted – Overdue Requirements state business logic
- [x] Stripe Account Rejected state UI
- [x] Stripe Account Rejected state business logic
- [x] Add "Dismiss" button to "Stripe Account Pending Requirements" screen - also consider using "Skip for now" instead of "Dismiss" 
- [x]  Generic Error Screen (designs tbd)
- [x] Pending requirements screen - "by [DATE]" is always empty

- [x] Add "Contact support" button listeners
- [x] Introduce new fragment with two simple rows "Manage Card Reader and Order Card Reader" 
- [x] Ordering Card Reader flow (load webview - consider if we need the list of readers, since there is currently only one reader merchants can buy)
- [x] Add tracking
- [x] Remove feature flag
- [x] Fix redirection from OrderDetail screen
- [x] Add dark theme version of illustration on onboarding loading screen (per https://github.com/woocommerce/woocommerce-android/pull/4554#pullrequestreview-723320378)
