### ISSUE TITLE
CPP Onboarding: Epic Phase 2

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce-android#4579]
Parent issue https://github.com/woocommerce/woocommerce-android/issues/4413

- [x] Live Account in Test Mode state UI
- [x] Live Account in Test Mode state business logic
- [x] ~Increase minimum required version of WCPay to 2.9.0 to handle BEGIN_OBJECT expected (waiting for release of wcpay 2.9.0)~ We decided not to increase the required version, because it wouldn't solve the issue for users who don't use in person payments
- [ ] Show onboarding "Collect payments with a Stripe card reader" dialog on OrderDetail (in progress @malinajirka )
