### ISSUE TITLE
Jetpack CP: install Jetpack from the app

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#4865]
Add ability to install Jetpack plugin from the app for site administrators

**Temporary designs:** (displaying detailed progress might not be possible)
<img width="837" alt="Screen Shot 2021-09-27 at 11 35 00" src="https://user-images.githubusercontent.com/1657201/134893002-557c8ceb-3f6e-4c61-ac53-ba91a7bde256.png">

**Comment by hafizrahman** [comment]
I'm breaking down the task into these smaller tasks (subject to changes):

### FluxC part:
- [x] PluginStore and REST Client https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2164

### WooMobile part:
- [x] Dialogs creation, navigation, and design. https://github.com/woocommerce/woocommerce-android/pull/5170
- [x] Adding actual plugin install functionality #5287
- [x] Connect UI with functionality #5325
- [x] Add retry functionality #5360 
- [ ] Add post-success or -failure state and functionality. Design and add install failure state for the UI https://github.com/woocommerce/woocommerce-android/pull/5609
- [ ] Add "Connecting" / Jetpack sync step. https://github.com/woocommerce/woocommerce-android/pull/5609
- [ ] Add tracks.
