### ISSUE TITLE
📦  Order List filters

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#4934]
Enable filtering orders by status or date range. This task also included a new design for the screen were tabs will be removed and a single order list will be displayed. 

More details p91TBi-5L9-p2

### 💻  Tasks

- [x] Enable filtering by order status: 
       - Part I:  #5039
       - Part II  #5087
- [x] Add filter for given ranges: Today, Last 2 Days, This Week, This Month: 
      - WooCommerce changes #5104 
      - FluxC changes [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2167)
- [x] Split order filters view model into 2 independent view models and properly handle state recovery on activity recreation: #5140
- [x] Save selected filters on disk to be kept across app sessions: #5169

To be done last 
- [x] Define and implement tracking: #5220
- [x] Have a single order list, remove tabs and apply always any filter selection to order list: #5219 
- [x] Remove status filters from search view and fix UI glitches between search feature and new filters button: #5239

Once the previous tasks are done, review if we still want to add this. 

- [x] Add filter for custom date range: #5260

### Design overview

![Screenshot 2021-10-05 at 09 52 13](https://user-images.githubusercontent.com/2663464/135982638-8414b89d-8a00-499d-9b2b-2e358ea76b0f.png)

![Screenshot 2021-10-05 at 13 02 19](https://user-images.githubusercontent.com/2663464/136011117-e516b206-d710-45a9-ac7a-86203eb6ee0e.png)
