### ISSUE TITLE
Wire up WordPress.com push notifications

### ISSUE THREAD

**Issue by aforcier** [woocommerce/woocommerce-android#501]
Once server-side filtering work is complete, we can enable incoming push notifications from WordPress.com. There are two kinds:

* A 'New order' notification, which does not stack and tapping it opens the order detail view for that order (it will be necessary to do a single order fetch to accomplish this)
* A 'Product reviewed' notification, which may or may not stack and should open the comment editing view (part of the work done in #37)

### To-do list (WIP)
* [x] Only ever show one New order notification, and update currently shown one if a new ones comes through --> Implemented in https://github.com/woocommerce/woocommerce-android/pull/531
* [x] Stack notifications inbox-style (like WPAndroid) --> Implemented in https://github.com/woocommerce/woocommerce-android/pull/531
* [x] Add basic processing service to handle cleanup on notification dismissal --> Implemented in https://github.com/woocommerce/woocommerce-android/pull/531
* [x] Support decompressing note data from bundle into a `NotificationModel` ~(see [WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/blob/dab184dbb277aee88ee818eff18c13908bf15f12/WordPress/src/main/java/org/wordpress/android/push/GCMMessageService.java#L397) - we could probably add this to FluxC)~
**edit: this has been added to FluxC during the NotificationsUI project**
* [x] Sync/fetch note in FluxC upon arrival (requires above item)
* [x] Update chime sound for 'new order' notification (tracked in #40)
* [x] Possibly modify new order push notification text (title is now overridden to "WooCommerce")
* [x] Analytics (basics done in #532) (finished in #604)
