### ISSUE TITLE
[Analytics] Add option to display revenue/orders/products for a store

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#5237]
As part of the Analytics project, we want to display the revenue/orders and products for a given date range of a store.

<img alt="Screenshot 2021-11-15 at 11 02 48 AM" src="https://user-images.githubusercontent.com/22608780/141727974-1a5405d4-988d-4749-b582-06a52c0e8ca8.png">

**Tasks to be completed**
- [x] Add a date range selector at the top of the screen. Default data to be displayed would be the current day data.
- [x] Display the Revenue card. This includes, for a given date range:
	- [x] 	The total sales and Net Sales.
	- [x] The % of sales compared to the previous date range
	- [x] The `See Report` button would redirect to the`wp-admin` for the particular report.
- [x] Display the Orders card. This includes, for a given date range:
	- [x] 	The total orders and Average Order Value.
	- [x] The % value compared to the previous date range.
	- [x] The `See Report` button would redirect to the`wp-admin` for the particular report.

**Note that the graph can be ignored for now.**
- [x] Display the Products card. This includes, for a given date range:
	- [x] 	The total items sold.
	- [x] The list of products + the quantity of that product sold.
	- [x] The `See Report` button would redirect to the`wp-admin` for the particular report.

Clicking on the Date rage would display a dialog with these options (similar to Core):
<img width="222" alt="Screenshot 2021-11-15 at 11 12 48 AM" src="https://user-images.githubusercontent.com/22608780/141728626-c0842dcd-f7f5-40e6-ab85-b84dff81fad2.png">

**The custom option can be removed for now, when implementing**

**Comment by anitaa1990** [comment]
@colymore, can you mark all the items in the issue description, that you have completed so far? That way, it's easier to keep track of what's done and what is pending 😊

**Comment by rfermontero** [comment]
At this point this is the state of the nation:


> **Tasks to be completed**
> 
> * [X]  Add a date range selector at the top of the screen. Default data to be displayed would be the current day data.
> * [X]  Display the Revenue card. This includes, for a given date range:
>   
>   * [X]  	The total sales and Net Sales.
>   * [X]  The % of sales compared to the previous date range
>   * [X]  The `See Report` button would redirect to the`wp-admin` for the particular report.
> * [-]  Display the Orders card. This includes, for a given date range:  **PENDING MERGE #5437** 
>  
>   * [X]  	The total orders and Average Order Value.
>   * [X]  The % value compared to the previous date range.
>   * [X]  The `See Report` button would redirect to the`wp-admin` for the particular report.
> 
> * [X]  Display the Products card. This includes, for a given date range:  >   
>   * [X]  The total items sold. 
>   * [X]  The list of products + the quantity of that product sold.
>   * [X]  The `See Report` button would redirect to the`wp-admin` for the particular report.
>
