### ISSUE TITLE
[Home Screen updates - Inbox] Implement the Inbox View

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#5877]
We should implement the view (in SwiftUI) displaying all the entries of the Inbox notifications.
Feel free to split the task in subtasks.
Figma is always the source of truth: vbzgTKHV9XsyyN5cxxAuhv-fi-443%3A8556

dark | light
-- | --
<img width="268" alt="Screen Shot 2022-02-11 at 9 21 55 AM" src="https://user-images.githubusercontent.com/1945542/153523900-5c7a4d15-45a2-44e8-81b0-3832de944944.png"> | <img width="267" alt="Screen Shot 2022-02-11 at 9 22 05 AM" src="https://user-images.githubusercontent.com/1945542/153523910-211b50bb-a46f-4e84-bf25-2288e3ffbc48.png">

## Subtasks

- [x] Add header with icon and relative date
- [x] Update empty state vbzgTKHV9XsyyN5cxxAuhv-fi-443%3A14458 
- [x] Update placeholder state to show content label

dark | light
-- | --
<img width="398" alt="Screen Shot 2022-02-10 at 3 55 17 PM" src="https://user-images.githubusercontent.com/1945542/153363450-92d24e3c-e06c-4b50-b24c-ae0dcac8338f.png"> | <img width="267" alt="Screen Shot 2022-02-10 at 3 55 40 PM" src="https://user-images.githubusercontent.com/1945542/153363472-def793e2-6658-4672-a482-75857e93a440.png">
