### ISSUE TITLE
Refactor SitePicker screens to MVVM

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce-android#6111]
This master issue lists the changes we need to migrate the site picker screen to use MVVM. 
## FluxC
- [x] Migrate fetch supported woo version methods into a suspendable function ([#2331](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2331)).
- [x] Migrate fetch site settings methods into a suspendable function ([#2332](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2332)).
- [x] Migrate fetch site product settings methods into a suspendable function ([#2332](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2332)).

## Woo
- [x] Update existing methods in Woo that fetch site settings & product settings remove usages of [deprecated event bus architecture](https://github.com/wordpress-mobile/WordPress-FluxC-Android/wiki/%5BDeprecated%5D-Architecture). (#6284 )
- [ ] Since the `SIGN OUT` action is the only action in the site picker that is utilising event bus, I thought of moving it to a separate class for now. It looks like the `AccountStore` is completely in Java and migrating the sign out action to suspendable is out of scope for this task.
- [x] Create a `SitePickerRepository` to communicate with FluxC to fetch site related details from the API.
- [x] Create a `ViewModel` that handles business logic for the Site picker screens.
- [x] Update the fragment classes and remove legacy code.
