### ISSUE TITLE
Notifications: Mark II

### ISSUE THREAD

**Issue by AmandaRiu** [woocommerce/woocommerce-android#619]
This second round of work will implement additional notification features and improvements.

### Notifications UI
- [x] Update notifications syncing logic #581
- [x] Mark all as read #627 

### Push Notifications
- [x] Unseen notifications concern #95 
~[ ] Investigate whether we need a NotificationsUpdateService #613~ keep as standalone task for future work. MVLP is finished. 
- [x] Add badges and logic #580
