### ISSUE TITLE
Store Stats

### ISSUE THREAD

**Issue by astralbodies** [woocommerce/woocommerce-android#65]
As a store owner I want to see quick stats about my stores performance within the app so I can know how well my business is doing: revenue, visitors, orders volume.

iOS equivalent epic: https://github.com/woocommerce/woocommerce-ios/issues/15

![dashboard-stats](https://user-images.githubusercontent.com/9613966/39319690-cdc1a5ac-494f-11e8-9cf6-1203debd6dad.png)

TODO:
* [x] Spike: Validate API expectations
* [x] Spike: See what can be reused from WPAndroid
* [x] Spike: Find graphing library to use
* [x] Scrollable segmented control component for card header (#274)
* [x] Store stats card header - Today / Week / Month / Year / Years (#274)
* [x] Add order revenue/sales stats to FluxC -> #203
* [x] Add graph with revenue data (month-to-date only)
* [x] Apply styling to graph
* [x] Display Sales/Revenue sum fields
* [x] Update with new time period segmentation (https://github.com/woocommerce/woocommerce-android/issues/242)
* [x] Support other timeframes in graph (#274)
* [x] Update graph styling (different color for weekend days, gridline changes (tracked in #261)
* [x] Format revenue total and y-axis currency values with k values when appropriate, and correctly localize (also relates to #148) (tracked in #261)
* [x] Add visitor stats to FluxC (`/rest/v1.1/sites/$site/stats/visits/`) (tracked in #275)
* [x] Display Visitors sum field (tracked in #275)

From MVLP discussion: Provide a quick glance at important sales-related information that makes app users want to come back often to see how things are going.

Stick with the data available through the WordPress.com API, not through the Jetpack tunnel.

(There are more possibilities from the current iOS app we can draw from for future iterations:
Revenue, New Orders, New Customers, Top Selling Items, Processed Orders, Pending Orders, Held Orders.)
