### ISSUE TITLE
[Unified Order Editing] Refactor Order Creation form to be used with an existing order

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#6613]
The order creation form should be able to take an existing order and render it correctly.

# Tasks:

- [x] Refactor names so they are not only valid for order creation. #6931 
- [x] Refactor form to receive an existing order. #6637
- [x] Check that no price is re-calculated when the form is opened. #6942 
- [x] Updates notices so they are not only valid for order creation. #6950

**Comment by shiki** [comment]
@atorresveiga I saw you mentioned this in your standup but you're not assigned. Is this what you're working on? Also, do you have any updates on the progress?
