### ISSUE TITLE
[Unified Order Editing] Handle multiple shipping lines edit

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#6653]
# Description

Our current `Order Creation` form only supports one custom shipping line.

Ref: pe5pgL-4W-p2

# Task

- [ ] Allow edition of only the first shipping line
- [ ] Allow deletion of only the first shipping line
- [ ] Make sure all shipping lines are calculated in the totals.
