### ISSUE TITLE
Localization Tooling Improvements Checklist

### ISSUE THREAD

**Issue by mokagio** [woocommerce/woocommerce-android#6663]
A semi-ordered checklist of steps for @mokagio to take to complete the localization tooling improvements. 

- [x] Use Fastlane APIs to add, commit, and push the localized metadata. See note in #6662. (Done: https://github.com/woocommerce/woocommerce-android/pull/6680)
- [ ] Compare `localize_libs` with WordPress Android `localize_libraries` – WIP #6742
- [ ] Compare `send_strings_for_translation` with WordPress Android `update_frozen_strings_for_translation` – WIP #6742
- [x] Remove custom `android_update_metadata_source` action. See https://github.com/wordpress-mobile/WordPress-Android/pull/16404. (Done: https://github.com/woocommerce/woocommerce-android/pull/6380)
-  _I'm 100% sure there's more stuff to update and convert. Stay tuned..._

Notes:

- `update_appstore_strings` is a lane we call manually as part of the release finalization process

**Comment by mokagio** [comment]
~~Also don't forget about https://github.com/woocommerce/woocommerce-android/pull/3821~~ Update: We didn't, but it turned out the changes proposed in that PR had already been implemented since it was opened.

**Comment by JorgeMucientes** [comment]
Closing this as part of the GitHub issue cleanup because it matches the stale-cleanup criteria used for this pass: older than two years, already marked in the audit as a close candidate, not Sentry-linked, and outside the protected external-human, POS, payments, and order-creation groups. If this is still relevant in current versions, please reopen with updated context.
