### ISSUE TITLE
[Unified Order Editing] Update Analytics

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#6711]
# Description

The current order creation form fires analytics only for the order creation domain, however, most events are engineered to support both modes, specifying them with the `flow: editing` property.

Additionally, we need to add and update some events to work with edition mode.

# Tasks

- [x] Update the codebase to fire the following events with the `flow: editing` when required. #6930
   - *_order_product_add
   - *_order_customer_add
   - *_order_fee_add
   - *_order_shipping_method_add
   - *_order_note_add
   - *_order_status_change

~- [ ] Rename the following events:~
   ~- *_order_create_button_tapped ----> *_order_save_button_tapped~
   ~- *_order_creation_success -----> *_order_save_success~
   ~- *_order_creation_failed -----> *_order_save_failed~

~- [ ] Update the following events to have the `flow: creation|editing` property and fire them when required.~
   ~- *_order_save_button_tapped~
   ~- *_order_save_success~
   ~- *_order_save_failed~
   
- [x] Update the following events to have the `flow: creation|editing` property and fire them when required. #6970
   - *_order_sync_failed

- [x] Add the following new events with the `flow: creation|editing` property and fire them when required. #6966
   - *_order_product_quantity_change
   - *_order_product_remove
   - *_order_fee_remove
   - *_order_shipping_method_remove

- [x] Add and fire the following new event with properties #6969
   - *_order_edit_button_tapped with params:
     - has_multiple_shipping_lines: Bool
     - has_multiple_fee_lines: Bool

**Comment by Ecarrion** [comment]
Updated events to remove
> *_order_create_button_tapped ----> *_order_save_button_tapped
*_order_creation_success -----> *_order_save_success
*_order_creation_failed -----> *_order_save_failed

As the order editing does not performs actions on save/done anymore.

**Comment by ealeksandrov** [comment]
Updated `*_order_edit_button_tapped` to have 2 params as agreed in p1657797905608349-slack-C02KUCFCSFP.
