### ISSUE TITLE
[Unified Order Editing] Adjust loading Indicators

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#6812]
# Description 

On **Order Creation** we display a loading indicator on the **Payments Section** to indicate that taxes are being recalculated.
That experience does not fit that well now that **Order Edition** commits all changes immediately and the changes do not necessarily affect taxes.

# Tasks

- [x] Only for **Order Edition**, move the loading indicator to the bottom of the navigation bar,
 while a remote action is performed.
- [x] Disable "Done" button while the loading indicator is being shown
- [x] Do not show loading indicator next to the **Payment Section**

https://user-images.githubusercontent.com/562080/175663520-70c309f3-6e89-4ed4-a643-0ddaaef13abc.mov
