### ISSUE TITLE
Kotlin Warnings as Errors - Woo Commerce Module

### ISSUE THREAD

**Issue by ParaskP7** [woocommerce/woocommerce-android#6819]
Parent #6816

This issue is about resolving/suppressing the Kotlin compile warnings for the `WooCommerce` module.

- [ ] Resolve/Suppress all warnings. @ParaskP7 ⚙️ 
  - [x] Resolve/Suppress `Coroutines` related warnings. @ParaskP7 #6840
    1. This declaration is experimental and its usage should be marked with `@kotlinx.coroutines.ExperimentalCoroutinesApi` or `@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)`
    2. This declaration is in a preview state and can be changed in a backwards-incompatible manner with a best-effort migration. Its usage should be marked with`@kotlinx.coroutines.FlowPreview` or `@OptIn(kotlinx.coroutines.FlowPreview::class)` if you accept the drawback of relying on preview API
  - [x] Resolve/Suppress `Deprecated` related warnings. @ParaskP7 #6850
    1. `toLowerCase(...): String` is deprecated. Use lowercase() instead.
    2. `Xyz` is deprecated. Deprecated in Java
    3. `Xyz` is deprecated. Other
    4. Candidate resolution will be changed soon, please use fully qualified name to invoke the following closer candidate explicitly
  - [x] Resolve/Suppress `Type/Cast/When` related warnings. @ParaskP7 #6865
    - Type
      1. Unsafe use of a nullable receiver of type Xyz?
      2. Returning type parameter has been inferred to Nothing implicitly because Nothing is more specific than specified expected type. Please specify type arguments explicitly in accordance with expected type to hide this warning. Nothing can produce an exception at runtime. See KT-36776 for more details.
      3. Type mismatch: inferred type is Date? but Date was expected
      5. Elvis operator (?:) always returns the left operand of non-nullable type Boolean
      6. Unnecessary safe call on a non-null receiver
    - Cast
      1. Smart cast to `Xyz` is deprecated, because 'itemView' is a property declared in base class from different module
      2. Unchecked cast: Any to T
      3. No cast needed
    - When
      1. Non exhaustive 'when' statements
      2. 'when' is exhaustive so 'else' is redundant here
  - [x] Resolve/Suppress `Other` related warnings. @ParaskP7 #6865
    1. This is a delicate API and its use requires care. Make sure you fully read and understand documentation of the declaration that is marked as a delicate API.
    2. Parameter `xyz` is never used
    3. Name shadowed: payload
    4. Property would not be serialized into a `Parcel`. Add `@IgnoredOnParcel` annotation to remove the warning (#6895)
    5. Parcelize annotations from package `kotlinx.android.parcel` are deprecated. Change package to `kotlinx.parcelize`
  - [x] Resolve/Suppress `Test` related warnings. @ParaskP7 #6902
    - Coroutines
        1. This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ExperimentalCoroutinesApi' or '@OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)'
        2. 'runBlockingTest(suspend TestCoroutineScope.() -> Unit): Unit' is deprecated. Use `runTest` instead to support completing from other dispatchers. Please see the migration guide for details: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md (#6899)
        3. 'advanceTimeBy(Long): Unit' is deprecated. The name of this function is misleading: it not only advances the time, but also runs the tasks scheduled *at* the ending moment. (#6899)
        4. 'TestCoroutineDispatcher' is deprecated. The execution order of `TestCoroutineDispatcher` can be confusing, and the mechanism of pausing is typically misunderstood. Please use `StandardTestDispatcher` or `UnconfinedTestDispatcher` instead. (#6899)
        5. 'TestCoroutineScope(CoroutineContext = ...): TestCoroutineScope' is deprecated. This constructs a `TestCoroutineScope` with a deprecated `CoroutineDispatcher` by default. Please use `createTestCoroutineScope` instead. (#6899)
        6. 'runBlockingTest(CoroutineContext = ..., suspend TestCoroutineScope.() -> Unit): Unit' is deprecated. Use `runTest` instead to support completing from other dispatchers. Please see the migration guide for details: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-test/MIGRATION.md
    - Other
        1. 'XYX' is deprecated. Deprecated in Java
        2. Unchecked cast: Xyz to Xyz
        3. Parameter 'xyz' is never used
        4. Parameter 'xyz' is never used, could be renamed to _
        5. Name contains characters which can cause problems on Windows: " 
- [x] Enable all warnings as errors. @ParaskP7 #6902
