### ISSUE TITLE
[Order Meta Data] Handle complex order metadata

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#6938]
We need to handle different kinds of values in order metadata (as defined in 213-gh-woocommerce/woomobile-private):

- [x] Discard empty values.
- [x] Discard JSON values.
- [x] Strip HTML from strings.
- 🚫  Detect when the value is a URL and make it tappable, opening the URL in an internal browser. (will be tackled in a different task since it will be a UI layer operation instead of something handled at the FluxC layer)

**Comment by shiki** [comment]
@ThomazFB I see that this is in the Done column, but it's not closed. 😛 

![](https://media.giphy.com/media/l0HluVRlGyuCOYQhi/giphy.gif)

**Comment by ThomazFB** [comment]
I have no idea what you're talking about..........
![image](https://user-images.githubusercontent.com/5920403/179639842-7784de1c-5807-4d5e-9a1b-9d9a692e854a.png)

**Comment by ThomazFB** [comment]
Issue closed by [PR on the FluxC side](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2469)
