### ISSUE TITLE
[Widgets] Fetch and Share data store info

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#7273]
# Description

When requesting fresh data for the widget, we need to make sure we store such data in a way it is accessible to the widget.

# Tasks

- [ ] Provide a way for the widget to fire the update data request
- [ ] Store data in a way the widget can read it later
- [ ] Make sure the widget is refreshing data periodically. Freshes Time TBD.
