### ISSUE TITLE
Today's Stats Widget Checklist

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#7288]
- [x] Import pre-existing widget code
- [x] Update to Hilt
- [x] Update to view binding
- [x] Ensure app builds even if widget doesn't work
- [x] Ensure widget appears even if data isn't fetched (see step below)
- [x] Drop light/dark mode selection and support the device's dark mode setting
- [x] Update to always use selected site
- [x] Detect when selected site has changed
- [x] Detect when user has logged out
- [x] Update to new methods for fetching revenue stats & visitors
- [x] Make sure refresh frequency is 30min
- [x] Refresh the widget when stats are refreshed in the app
- [x] Fix revenue rounding
- [x] Test on Lollipop
- [x] Improve logged out experience
- [x] Analytics 
- [x] Add last refreshed label 
- [x] Run test plan
- [x] Add to release notes
- [x] Add to What's New, along with instructions for adding it
