### ISSUE TITLE
Login: Open Login Help Center when user selects the option coming from login-related screen

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#7318]
We're making a new login-related help page:

https://woocommerce.com/document/android-ios-apps-login-help-faq/

The help page have specific sections that maps to specific login-related screen. Let's make it so that if users are in the following screen, then taps the Help icon, then select "Help Center", they are directed to the right sections on the help page above:

- [x] Enter Your Store Address #7312 
- [x]  Enter WordPress.com Email Address (Login using store address flow) #7319
- [x]  Login with WordPress.com #7319
- [x]  Enter Store Credentials #7319
- [ ]  Jetpack Required #7320
- [ ]  Enter WordPress.com Password
- [ ]  Open mail
- [ ]  Pick Store After Entering Password

(Internal ref: pe5sF9-sZ-p2)
