### ISSUE TITLE
WooCommerce Account Creation

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#7510]
### Description 
Create a new screen that given an email and password creates a new WordPress account

### Tasks

- [x] Add new "Get Started" button to prologue under feature flag that opens new Sign Up screen:  #7534 
- [x] Create new screen with given UI: #7534 
- [x] Add API requests for happy path: [FluxC PR](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2544) and #7565
- [x] Error handling: #7584
- [x] Tracking #7673
- [x] Trigger store creation flow after successful signup  #7662 
- [x] Handle "Log in" CTA navigation to log in with WP.com credentials #7662 

### Designs 

![Screenshot 2022-10-11 at 15 05 29](https://user-images.githubusercontent.com/2663464/195098834-59e459c6-72c0-4d96-bfb6-436a723681ed.png)
