### ISSUE TITLE
[Just In Time Messages] Dismiss JITM when x tapped

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-android#7530]
## Description
JITMs can be dismissed, and dismissal will result in them not being sent again by the server until 
- their next display interval is reached
- up to a maximum of n dismissals (usually 2).

To achieve that, we must make a request to the server to report that the user has dismissed the message.

## Tasks
- [ ] Dismiss UI for JITM when x is tapped
- [x] #7590
- [ ] Track `*_jitm_dismissed` event with props `jitm_group: {FEATURE_CLASS}`, `jitm_id: {JITM_ID}`, `source: my_store`
- [ ] Track `*_jitm_dismiss_success` event with props `jitm_group: {FEATURE_CLASS}`, `jitm_id: {JITM_ID}`, `source: my_store`
- [ ] Track `*_jitm_dismiss_failure` event with props `jitm_group: {FEATURE_CLASS}`, `jitm_id: {JITM_ID}`, `source: my_store` and standard error props
- [ ] #7618

## Further Reading
- pdfdoF-1uc-p2 
- pdfdoF-1vt-p2

**Comment by JorgeMucientes** [comment]
Closing this as part of a maintenance pass on the GitHub issue backlog. This issue matched the auto-close criteria for this pass: it has not been updated since 2022-10-28, is unassigned, is not labeled as a bug or high/medium priority, and does not appear to involve POS, payments, login, data loss, crash, security, vulnerability, auth, or fraud.

If this is still relevant, please comment with current details and we can reopen it or move it into Linear for triage.
