### ISSUE TITLE
[Just In Time Messages] Open JITM link in webview when CTA tapped

### ISSUE THREAD

**Issue by joshheald** [woocommerce/woocommerce-android#7531]
## Description
JITMs contain a link for the CTA, which we should open in a webview to allow the merchant to take action on a given JITM.

## Tasks
- [ ] Set appropriate UTM parameters on the URL (`CTA.link` on the JITM), initially only for WooCommerce.com links. See pdfdoF-1yo-p2 or below for detail.  
- [ ] Open the JITM's link in a modal webview.
- [ ] Use an AuthenticatedWebview for WooCommerce.com links
- [ ] Track `*_jitm_cta_tapped` event with props `jitm_group: {FEATURE_CLASS}`, `jitm_id: {JITM_ID}`, `source: my_store`

### UTM params
- `utm_medium`: `woo_android`
- `utm_campaign`: `jitm_group_{FEATURE_CLASS}` i.e. `jitm_group_woomobile_ipp`
- `utm_source`: `my_store`
- `utm_term`: Blog ID
- `utm_content`: `jitm_{JITM_ID}` i.e. `jitm_woomobile_ipp_barcode_users`

## Further Reading
- pdfdoF-1uc-p2 
- pdfdoF-1vt-p2

**Comment by audreyspency** [comment]
how's that got solved

**Comment by JorgeMucientes** [comment]
Closing as part of the Woo Mobile GitHub stale-issue audit cleanup.

Rationale for closing:
- Listed in audit section "Potentially Stale / Good Candidates To Close Still Open (37)". Last GitHub activity in the audit: 2023-07-17 1081d. Audit recommendation: Close candidate. Audit rationale: Close candidate: stale metadata supports closure, but No direct current-code signal found; manual product triage recommended.. Audit evidence: No GitHub activity for 1081 days (>2 years).. No longer in a protected grouped area in this report; close as stale backlog cleanup and reopen if still reproducible or product-owned.

Reopen if this is still reproducible, product-owned, or should be tracked in a current Linear issue.
