### ISSUE TITLE
[Analytics Hub] Implement Jetpack Visitors and Views stats card

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#7574]
This issue should implement the following tasks:

- [x] Basic card UI (https://github.com/woocommerce/woocommerce-android/pull/7730)
- [x] Basic Data fetching (https://github.com/woocommerce/woocommerce-android/pull/7730)
- [x] Day, week, month and year date range selection (https://github.com/woocommerce/woocommerce-android/pull/7730)
- [x] Quarter date range selection (https://github.com/woocommerce/woocommerce-android/issues/7750)
- [x] Hide Visitors and Stats when Custom date range is selected (https://github.com/woocommerce/woocommerce-android/issues/7780)
- [x] Delta percentage badge info (https://github.com/woocommerce/woocommerce-android/issues/7751)
- [x] Sentry performance monitoring and tracks (https://github.com/woocommerce/woocommerce-android/pull/7801)
