### ISSUE TITLE
Domain Selection in Store Creation Flow

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#7720]
Add new domain selection step following design from HyVloP5FipZzyPVenH2euI-fi-1579%3A83494

![Screenshot 2022-11-02 at 11 00 15](https://user-images.githubusercontent.com/2663464/199461477-716a7fdb-dab2-4476-823a-c94ef4e33aa4.png)

### UI
- [x] Choose domain screen -> #7732
- [x] My store final screen -> #7802
- [x] Error handling -> #7879

### Network

- [x] Fetch domain suggestions -> #7761
