### ISSUE TITLE
Groundskeeping Android Master Issue: Feb 8 - 22

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#808]
### WooCommerce Issues

- [x] #786 Crash in Tracks (PR #804)
- [x] #329 MPAndroidChart library does not yet support RTL
- [x] #787 LoginActivity.addGoogleLoginFragment – Can not perform this action after onSaveInstanceState (PR #809)
- [x] #782 Fatal Exception: java.lang.IllegalStateException – MainNavigationView.clearFragmentBackStack (PR #810)
- [x] #749 Zendesk icon takes you out of app from "My Tickets" 
- [x] #750 Misleading UI when using site URL to login (PR #813)
- [x] #814 Add order notes doesn't capitalize the first letter (PR #815)
- [ ] #447 WCStatsStore IllegalStateException - Missing field from stats endpoint
- [x] #818 Can't go back to My Store after viewing a pending order (PR #819)
- [ ] #822 Error inflating class com.woocommerce.android.ui.main.MainNavigationView 
- [x] #828 Change “Log out account” to “Log Out” (PR #831)
- [x] #829 On Top Performers list change “Total product order” to “Total orders” (PR #830)
- [x] #659 IllegalStateException: Fragment has not been attached yet (PR #832)

**Comment by astralbodies** [comment]
![i-love-it](https://user-images.githubusercontent.com/373903/53094558-1455d980-34e0-11e9-8f61-f9cc9f2c32c3.gif)

**Comment by nbradbury** [comment]
Closing this since my groundskeeping rotation is complete.
