### ISSUE TITLE
[REST API] Site Credentials login flow

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#8110]
For the REST API project, the authentication will use the site credentials before generating the Application Password that will be used for subsequent requests, and for this, we need to rework the site credentials screen to allow the following:

- [x] Create a new site credentials screen, this screen will be specific to the WCAndroid app for now. #8119 
- [x] Handle Authentication. #8119 
- [x] Fetch Site info. #8119 
- [x] Display an error if the site is not a WooCommerce site. #8125
- [x] Display an error if application passwords are disabled. #8150  
- [x] Display an error if the user's role doesn't allow using the app. #8156
- [x] Unit tests. #8171
