### ISSUE TITLE
Activate: Domain change

### ISSUE THREAD

**Issue by 0nko** [woocommerce/woocommerce-android#8238]
Spike: pe5sF9-Ug-p2
Design: VyLr7LvKodHE4kINfBE7Lw

<img width="800" src="https://user-images.githubusercontent.com/1522856/214015128-9cd73146-f926-4757-b728-2416c8691ed4.png">

---

## Subtasks

- [x] https://github.com/woocommerce/woocommerce-android/pull/8215: Create a feature flag & add a CTA that navigates to the main UI if: 
  - The feature flag is enabled
  - The site is a wpcom site

#### UI

- [x] Show the free `*.wpcomstaging.com` URL at the top a possibility for the following below #8253: 
  - If no other domains, there are two CTAs, show a CTA to search for a domain that navigates to the next screen
  - If there are existing domains, show the list of domains for the site with a CTA to add another one which navigates to the next screen
  - If the site includes a domain credit, show the domain credit UI with a CTA to search for a domain using domain credit in the next screen
- [x] #8274 #8275
- Implemented in: #8297  
  - [x] #8278
  - [x] #8280
  - [x] #8281

#### FluxC

- [x] Implement the necessary changes in FluxC to facilitate the fetching of domains and plans with all the required data wordpress-mobile/WordPress-FluxC-Android#2646
- [x] Implement the functionality to fetch a price for a specific domain wordpress-mobile/WordPress-FluxC-Android#2652

### Domain selector screen

- [x] #8272 #8273
- [x] #8338 #8348
  - Also load all the products and match them later with the domain suggestions to apply the proper discount: `https://public-api.wordpress.com/rest/v1.1/products?http_envelope=1&type=domains` 
- [x] #8356 #8360

### Domain registration screen

- Implemented in #8422:
- [x] #8407
- [x] #8408
- [x] #8409

### Success screen

- [x] #8366 #8367 

### Other

- [x] #8362 
- [x] #8373 
- [x] #8429
- [x] #8433 #8444
- [x] #8476 #8477

**Comment by ParaskP7** [comment]
FYI: @0nko I moved the `12.6` milestone to `12.7` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `12.6` release.

**Comment by 0nko** [comment]
Hi @ParaskP7! Actually, the issue has been completed and all tasks are finished, I just didn't get a chance to update the status. One thing I did forget was to update the changelog and remove a feature flag. Is it that okay to still put it in 12.6?

**Comment by ParaskP7** [comment]
👋 @0nko !

I issued the code freeze completion about 30' mins ago, dammit! 😅 

The new `12.6-rc-1` release has been uploaded to `Google Play Console` just now, but I think I can discard this release and trigger a new ~~code freeze completion~~ release build trigger after you apply your changes, I hope I can... 🤞 😅 

So, what you could do is create a PR that will target the new `release/12.6` branch of ours and apply those pending changes. Then, when those get reviewed and merged, I'll issue another code freeze completion. How does this sound to you? 🤔

PS: The only thing I will ask is to get all that work done as quickly as possible as I have 2 more hours before my EOD and I would like to complete the release steps for `12.6` for today before logging-off. 🙏

**Comment by ParaskP7** [comment]
FYI: @0nko I moved the `12.7` milestone to `12.8` in order to proceed with the code freezing process. Do let me know if you still need this issue to be part of the `12.7` release.
