### ISSUE TITLE
Display a list of onboarding tasks in My Store Tab 

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#8260]
### Design 

Figma files: VyLr7LvKodHE4kINfBE7Lw-fi-1327%3A76650

![Screenshot 2023-02-16 at 16 03 32](https://user-images.githubusercontent.com/2663464/219402105-c6c977ba-018f-4a17-9fe2-d5e5d53e8253.png)

### Behavior

- If all the onboarding tasks are completed except for Customize your domain we’ll display the onboarding list in a collapsed mode. 
- If all tasks are completed or the user proactively dismissed the onboarding list, we’ll hide the list.
- The status of the task completed/not completed shall be fetched from the API using the following path `/wc-admin/onboarding/tasks`. This path can be accessed through the Jetpack tunnel for example using WP console: `/jetpack-blogs/{site_id}/rest-api/?path=/wc-admin/onboarding/tasks`. The `isComplete` field from the response will serve as reference on the status of the task:
```json 
{
  "data": [
    {
      "id": "setup",
      "title": "Get ready to start selling",
      "isHidden": false,
      "isVisible": true,
      "isComplete": false,
      "tasks": [
        {
          "id": "store_details",
          "parentId": "setup",
          "title": "You added store details",
          "canView": true,
          "content": "Your store address is required to set the origin country for shipping, currencies, and payment options.",
          "additionalInfo": "",
          "actionLabel": "Let's go",
          "actionUrl": "https://proxied.site/wp-admin/admin.php?page=wc-settings&tab=general",
          "isComplete": true,
          "time": "4 minutes",
          "level": 3,
          "isActioned": false,
          "isDismissed": false,
          "isDismissable": false,
          "isSnoozed": false,
          "isSnoozeable": false,
          "isVisited": false,
          "isDisabled": false,
          "snoozedUntil": null,
          "additionalData": null,
          "eventPrefix": "tasklist_",
          "recordViewEvent": false
        }, ...
```
### Subtasks

- [x] Add a new card to My Store tab that displays a list of hard-coded onboarding tasks: https://github.com/woocommerce/woocommerce-android/pull/8265
- [x] Add list header with progress bar: https://github.com/woocommerce/woocommerce-android/pull/8265
- [x] Fetch onboarding tasks current status from the API and refresh the list accordingly: [FluxC changes ](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2661) and #8359
- [x] Add footer to expand list of tasks: #8385
- [x] Add Overflow button to dismiss the onboarding: #8410 
- [x] Add logic that determines when to show the onboarding list: Relying on the API response for now where we show the onboarding list if there's any incomplete task. #8359
- [x] Order onboarding tasks according to latest designs
