### ISSUE TITLE
[Support Requests] Integrate New UI + API Providers

### ISSUE THREAD

**Issue by ThomazFB** [woocommerce/woocommerce-android#8333]
# Task

- [ ] Integrate UI with new API - Provider Request
- [ ] Show loading indicators
- [ ] Show error notices.
- [ ] Alert users that they will be contacted via email next
