### ISSUE TITLE
Notification issue checklist

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#858]
We have quite a few notification-related issues to tackle. Tracking them here:

- [x]  #856 Crash in NotifsListFragment.revertPendingModeratedNotifState (PR #860)
- [x]  #845 UI issues when trashing last review (PR #860)
~~- [ ]  #844 Restored notifs don't show up~~ 
- [x]  #859 Problems when rapidly moderating reviews (PR #862)
- [x]  #837 Empty review detail (PR #842)
- [x]  #834 Tapped notification doesn't open detail (PR #857)
- [x]  #816 java.lang.IndexOutOfBoundsException in notif list (PR #851)

**Comment by AmandaRiu** [comment]
All items have been addressed. Closing.
