### ISSUE TITLE
[Privacy Choices] Link support docs in Privacy Screen

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#8939]
# UI

![Image](https://user-images.githubusercontent.com/562080/235844645-41374d8f-7fd5-4de4-8dde-4b1541274972.png)

# Tasks

Using the URLs provided in https://github.com/woocommerce/woomobile-private/issues/286

- [ ] Launch a webview when the user taps on the "Privacy Policy" link.
- [ ] Launch a webview when the user taps on the "Cookie Policy" link.
- [ ] Launch a webview when the user taps on the "Advertising Option" row.
