### ISSUE TITLE
[Privacy Choices] Keep analytics choice state up to date

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#8940]
Make sure the "Analytics" choice always reflects the latest status of the [`me/settings`](https://href.li/?https://developer.wordpress.com/docs/api/1.1/post/me/settings/) endpoint.

# Tasks

- [ ] Make sure to always sync the latest state when entering the privacy view
- [ ] Make sure to commit the new state after changing selection
- [ ] Show a notice + a retry when failing to get the latest selection state
- [ ] Show a notice + a retry when failing to commit the new selection
