### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by JorgeMucientes** [woocommerce/woocommerce-android#8955]
With the current policy updates from Google and now that we have enabled users to create new WordPress accounts from the Sign-Up flow we need to enable a way for them to delete the accounts. 

- [x] Close account UI from settings: #9033
- [x] Close account FluxC changes (new endpoint and rest client): [#2732](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2732)
- [x] Close account Woo app logic: #9034 
- [x] Add close account option from site picker: #9050

<img width="600"  src="https://user-images.githubusercontent.com/2663464/235967556-1b24ba2e-eb96-4c8d-ae31-ad1f0137b816.png"> 

For this feature we'll implement the same UX as iOS currently has:

https://user-images.githubusercontent.com/2663464/236266455-6ff7d3a6-cfef-4c04-96ca-b65764e3ed6a.MP4
