### ISSUE TITLE
[Privacy Choices] Update wording & Links

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#9109]
# Wording Review

![Image](https://user-images.githubusercontent.com/562080/240761058-e82934ab-7bf7-4e7c-b113-43719adfe529.png)

# Tasks

- [ ] Remove "and marketing activities" from the Privacy description
- [ ] Change the "Advertising Options" title to "Web Options"
- [ ] Change the "Usage Tracker" title to "Usage Tracking"
- [ ] Launch the [Tracking Opt-Outs support document](https://woocommerce.com/tracking-and-opt-outs/) from the "Web Options" menu.
