### ISSUE TITLE
Product detail master checklist

### ISSUE THREAD

**Issue by nbradbury** [woocommerce/woocommerce-android#913]
This checklist is to track the progress of the product detail feature.

- [x] Basic product detail (PR #914)
- [x] Share product (included in #914)
- [x] Link to product & affiliate (included in #914)
- [x] Retrieve dimension units (FluxC PR [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1184))
- [x] Add dimension units to product detail (included in #914)
- [x] Give the product image the same scrolling treatment we give media in WPAndroid (#927)
- [x] Add badge for unpublished products (#938)
- [x] Full screen product image viewer (#960)
- [x] Unit tests (PR #965)
- [x] Product variations (PR #984)
- [x] Set product detail title based on product type (PR #986)
- [x] Design review (#997)
- [x] Product detail analytics (#987)
- [x] Enable for all users (#998)

**Comment by jkmassel** [comment]
This is being bumped to 1.7. If it needs to ship sooner, please merge it to release/1.6, and let me know when you're ready for a hotfix release!

**Comment by nbradbury** [comment]
Closing this as all the child tasks have been completed and merged 🎉
