### ISSUE TITLE
Direct product discount

### ISSUE THREAD

**Issue by samiuelson** [woocommerce/woocommerce-android#9352]
```[tasklist]
### Tasks
- [x] Manual product discount feature
- [x] Percentage discount picker
- [ ] Analytics Events
- [ ] Prevent adding a discount in there are active coupons
- [ ] Add total discount amount text to the Payment section in Order Edit Mode
- [ ] Add discount value label to Order items in Order Edit mode
```
