### ISSUE TITLE
“Name your store” task in the Onboarding task list

### ISSUE THREAD

**Issue by hafizrahman** [woocommerce/woocommerce-android#9621]
![Screenshot 2023-08-21 at 12 35 22](https://github.com/woocommerce/woocommerce-android/assets/266376/7c247ea0-205e-49f7-ac32-2f4d2ad195df)

Tasks involved:

- [x] Set default name when creating new store as "Store Name" https://github.com/woocommerce/woocommerce-android/pull/9623
- [x] Create a new local onboarding task type `storeName` and add logic around it. https://github.com/woocommerce/woocommerce-android/pull/9627
- [x] Add UI for task above in the onboarding list and the dialog to edit it. https://github.com/woocommerce/woocommerce-android/pull/9628
- [x] Add functionality to handle store name input, checking task off of list. https://github.com/woocommerce/woocommerce-android/pull/9677
    - [x] Possibly requires FluxC change to save the store name. https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2820
- [x] Show notice after setting store name and add new Setting item for store name (see iOS https://github.com/woocommerce/woocommerce-ios/pull/10485) #9677
