### ISSUE TITLE
Gift cards support during order creation

### ISSUE THREAD

**Issue by atorresveiga** [woocommerce/woocommerce-android#9631]
Adding gift card support during order creation will provide a consistent experience for merchants, and it could increase the app’s revenue and engagement. This task is about researching if this support is possible, drafting a design inspired on wp-admin interaction, and developing an implementation.

> Need to support variable items, composite items, and bundled items. I can add these to the order via the website and the order shows up correctly in the app, but I can’t add them to the order via the app because they show up as $0.00 items.
```[tasklist]
### Pull Requests
- [ ] https://github.com/woocommerce/woocommerce-android/pull/10297
- [ ] https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2905
- [ ] https://github.com/woocommerce/woocommerce-android/pull/10221
- [ ] https://github.com/woocommerce/woocommerce-android/pull/10269
- [ ] https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2915
- [ ] https://github.com/woocommerce/woocommerce-android/pull/10337
```

```[tasklist]
### Tasks
- [x] Define Feature Flag
- [x] Add Gift card interaction inside Order Creation
- [x] Add network and storage layer for Gift Cards
- [x] Fix database migration crash blocking the storage layer changes
- [x] Handle gift card code submission
- [x] [Nice to have] Enforce gift card code format
- [ ] [Nice to have] Add code scanner
- [ ] Add Gift Card tracks
- [x] Remove Feature Flag
```

**Comment by jaclync** [comment]
iOS issue with task breakdown: https://github.com/woocommerce/woocommerce-ios/issues/10518

**Comment by atorresveiga** [comment]
@ThomazFB should we close this task?

**Comment by malinajirka** [comment]
Due to the lack of activity on this task, and the fact that the author suggested to close this task => closing now.
