### ISSUE TITLE
Nudge to set up WooPayments

### ISSUE THREAD

**Issue by hichamboushaba** [woocommerce/woocommerce-android#9688]
Update the flow of the WooPayments step in the store onboarding
pe5sF9-1VA-p2

Technical discussion: pe5sF9-1VU-p2

```[tasklist]
### Tasks
- [ ] https://github.com/woocommerce/woocommerce-android/issues/9694
- [ ] https://github.com/woocommerce/woocommerce-android/issues/9689
- [ ] https://github.com/woocommerce/woocommerce-android/issues/9706
- [ ] https://github.com/woocommerce/woocommerce-android/issues/9692
- [ ] https://github.com/woocommerce/woocommerce-android/issues/9713
- [ ] https://github.com/woocommerce/woocommerce-android/issues/9717
```
