### ISSUE TITLE
[Passkeys] Sign & Verify challenge in the device

### ISSUE THREAD

**Issue by Ecarrion** [woocommerce/woocommerce-android#9911]
Depends on

- #9909
- #9910

# Context

With the API endpoints ready, the device needs to orchestrate the `Continue with security key` flow.

# Task

- [ ] Request a challenge from the server when the user taps on the "Continue with security key" CTA.
- [ ] Invoke the device's native SDK to sign the server challenge
- [ ] Submit the signed challenge to the server
- [ ] Exit the login flow with the authenticated access token.
